//
// -----------------------------------------------------------------------------
// Copyright (c) 2011-2014 Qualcomm Atheros, Inc.  All rights reserved.
// -----------------------------------------------------------------------------
// FILE         : radio_top_reg_map.h
// DESCRIPTION  : Software Header File for WiFi 2.0
// THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT
// -----------------------------------------------------------------------------
//

#ifndef _RADIO_TOP_REG_MAP_H_
#define _RADIO_TOP_REG_MAP_H_


#ifndef __RADIO_TOP_REG_MAP_BASE_ADDRESS
#define __RADIO_TOP_REG_MAP_BASE_ADDRESS (0x46000)
#endif




#endif /* _RADIO_TOP_REG_MAP_H_ */
