// Copyright (c) 2014 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _TLV_TAG_DEF_H_
#define _TLV_TAG_DEF_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_TLV_TAG_DEF 1

struct tlv_tag_def {
};

/*
*/



#endif // _TLV_TAG_DEF_H_
