// This is an auto-generated file.
// DON'T manually modify the file but use cmdRspDictGenSrc.exe.

#include "tlv2Inc.h"

//Commands
CMD_DICT SysCmdDict[] = {

#ifdef USE_TLV2_SYSCMD

    {SYSCMD_FIRST_RAND},
    {SYSCMD_SETCHANNEL_RAND},
    {SYSCMD_SETCHANNELRSP_RAND},
    {SYSCMD_TESTDATA_RAND},
    {SYSCMD_TESTDATARSP_RAND},
    {SYSCMD_GENERIC_RAND},
    {SYSCMD_GENERICRSP_RAND},

#endif //USE_TLV2_SYSCMD

};

int MaxSysCmdDictEntries = (sizeof(SysCmdDict) / sizeof(CMD_DICT));

//Parameters
PARM_DICT SysParmDict[] = {

#ifdef USE_TLV2_SYSCMD

    {SYSPARM_FIRST_RAND, {(A_UINT32)255}, 0, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_PHY_MASK_RAND, {(A_UINT32)0}, 21, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_RADIO_MASK_RAND, {(A_UINT32)0}, 16, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_CROSSING_RAND, {(A_UINT32)0}, 11, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_XCONNECTION_RAND, {(A_UINT32)0}, 8, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_CENTER_CHANNEL_R0_RAND, {(A_UINT32)0}, 27, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_CENTER_CHANNEL_R1_RAND, {(A_UINT32)0}, 5, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_BW_R0_RAND, {(A_UINT32)0}, 17, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_BW_R1_RAND, {(A_UINT32)0}, 31, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_MODE_RAND, {(A_UINT32)0}, 18, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_PRIMARY_LOCATION_R0_RAND, {(A_UINT32)0}, 7, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_PRIMARY_LOCATION_R1_RAND, {(A_UINT32)0}, 28, DATATYPE(PARM_U8, TYPE_SINGULAR)},
    {SYSPARM_CAL_MASK_RAND, {(A_UINT32)0}, 0, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_FORCE_CAL_MASK_RAND, {(A_UINT32)0}, 9, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_DATA1_RAND, {(A_UINT32)NULL}, 18, DATATYPE(PARM_DATA_1024, TYPE_DATA)},
    {SYSPARM_DATA2_RAND, {(A_UINT32)NULL}, 28, DATATYPE(PARM_DATA_1024, TYPE_DATA)},
    {SYSPARM_DATA3_RAND, {(A_UINT32)NULL}, 2, DATATYPE(PARM_DATA_1024, TYPE_DATA)},
    {SYSPARM_DATA4_RAND, {(A_UINT32)NULL}, 12, DATATYPE(PARM_DATA_1024, TYPE_DATA)},
    {SYSPARM_STATUS32_RAND, {(A_UINT32)0}, 12, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_CMDID_RAND, {(A_UINT32)0}, 22, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_01_RAND, {(A_UINT32)0}, 7, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_02_RAND, {(A_UINT32)0}, 17, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_03_RAND, {(A_UINT32)0}, 27, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_04_RAND, {(A_UINT32)0}, 1, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_05_RAND, {(A_UINT32)0}, 11, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_06_RAND, {(A_UINT32)0}, 21, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_07_RAND, {(A_UINT32)0}, 31, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_08_RAND, {(A_UINT32)0}, 5, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_09_RAND, {(A_UINT32)0}, 15, DATATYPE(PARM_U32, TYPE_SINGULAR)},
    {SYSPARM_GENERIC_PARAM_10_RAND, {(A_UINT32)0}, 19, DATATYPE(PARM_U32, TYPE_SINGULAR)},

#endif //USE_TLV2_SYSCMD

};

int MaxSysParmDictEntries = (sizeof(SysParmDict) / sizeof(PARM_DICT));

