// This file is auto-updated when a command is added to the dictionary by running cmdRspDictGenSrc.exe

#include "tlv2Inc.h"
#include "cmdHandlers.h"

// Notes:
//
// TBD??? "dynamic" loading of the modules?
// Potentially we could allocate enough space for "dynamic" binding of the handlers, modularize them
//
// cmdHandlerTbl
// Note:
//     1. rspGeneration of the RSP should be NULL, otherwise, it will be response for RSP, an infinite loop

CMD_HANDLER_ENTRY CmdHandlerTbl[] = {
    {NULL, NULL, NULL},
    {initTPCCALOpParms, TPCCALOp, NULL},
    {initTPCCALRSPOpParms, TPCCALRSPOp, NULL},
    {initTPCCALPWROpParms, TPCCALPWROp, NULL},
    {initTPCCALDATAOpParms, TPCCALDATAOp, NULL},
    {initRXGAINCALOpParms, RXGAINCALOp, NULL},
    {initRXGAINCALRSPOpParms, RXGAINCALRSPOp, NULL},
    {initRXGAINCAL_SIGL_DONEOpParms, RXGAINCAL_SIGL_DONEOp, NULL},
    {initRXGAINCALRSP_DONEOpParms, RXGAINCALRSP_DONEOp, NULL},
    {initREGREADOpParms, REGREADOp, NULL},
    {initREGREADRSPOpParms, REGREADRSPOp, NULL},
    {initREGWRITEOpParms, REGWRITEOp, NULL},
    {initREGWRITERSPOpParms, REGWRITERSPOp, NULL},
    {initBASICRSPOpParms, BASICRSPOp, NULL},
    {initTXOpParms, TXOp, NULL},
    {initTXSTATUSOpParms, TXSTATUSOp, NULL},
    {initTXSTATUSRSPOpParms, TXSTATUSRSPOp, NULL},
    {initRXOpParms, RXOp, NULL},
    {initRXSTATUSOpParms, RXSTATUSOp, NULL},
    {initRXSTATUSRSPOpParms, RXSTATUSRSPOp, NULL},
    {initHWCALOpParms, HWCALOp, NULL},
    {initRXRSPOpParms, RXRSPOp, NULL},
    {initXTALCALPROCOpParms, XTALCALPROCOp, NULL},
    {initXTALCALPROCRSPOpParms, XTALCALPROCRSPOp, NULL},
    {initREADCUSTOTPSPACEOpParms, READCUSTOTPSPACEOp, NULL},
    {initREADCUSTOTPSPACERSPOpParms, READCUSTOTPSPACERSPOp, NULL},
    {initWRITECUSTOTPSPACEOpParms, WRITECUSTOTPSPACEOp, NULL},
    {initWRITECUSTOTPSPACERSPOpParms, WRITECUSTOTPSPACERSPOp, NULL},
    {initGETCUSTOTPSIZEOpParms, GETCUSTOTPSIZEOp, NULL},
    {initGETCUSTOTPSIZERSPOpParms, GETCUSTOTPSIZERSPOp, NULL},
    {initGETDPDCOMPLETEOpParms, GETDPDCOMPLETEOp, NULL},
    {initGETDPDCOMPLETERSPOpParms, GETDPDCOMPLETERSPOp, NULL},
    {initGETTGTPWROpParms, GETTGTPWROp, NULL},
    {initGETTGTPWRRSPOpParms, GETTGTPWRRSPOp, NULL},
    {initSETPCIECONFIGPARAMSOpParms, SETPCIECONFIGPARAMSOp, NULL},
    {initSETPCIECONFIGPARAMSRSPOpParms, SETPCIECONFIGPARAMSRSPOp, NULL},
    {initCOMMITOTPSTREAMOpParms, COMMITOTPSTREAMOp, NULL},
    {initCOMMITOTPSTREAMRSPOpParms, COMMITOTPSTREAMRSPOp, NULL},
    {initSETREGDMNOpParms, SETREGDMNOp, NULL},
    {initSETREGDMNRSPOpParms, SETREGDMNRSPOp, NULL},
    {initMEMWRITEOpParms, MEMWRITEOp, NULL},
    {initMEMWRITERSPOpParms, MEMWRITERSPOp, NULL},
    {initMEMREADOpParms, MEMREADOp, NULL},
    {initMEMREADRSPOpParms, MEMREADRSPOp, NULL},
    {initCONFIGOpParms, CONFIGOp, NULL},
    {initDPDLOOPBACKTIMINGOpParms, DPDLOOPBACKTIMINGOp, NULL},
    {initDPDLOOPBACKTIMINGRSPOpParms, DPDLOOPBACKTIMINGRSPOp, NULL},
    {initDPDLOOPBACKATTNOpParms, DPDLOOPBACKATTNOp, NULL},
    {initDPDLOOPBACKATTNRSPOpParms, DPDLOOPBACKATTNRSPOp, NULL},
    {initDPDTRAININGQUALITYOpParms, DPDTRAININGQUALITYOp, NULL},
    {initDPDTRAININGQUALITYRSPOpParms, DPDTRAININGQUALITYRSPOp, NULL},
    {initDPDAGC2PWROpParms, DPDAGC2PWROp, NULL},
    {initDPDAGC2PWRRSPOpParms, DPDAGC2PWRRSPOp, NULL},
    {initLMHWCALOpParms, LMHWCALOp, NULL},
    {initLMHWCALRSPOpParms, LMHWCALRSPOp, NULL},
    {initLMTXOpParms, LMTXOp, NULL},
    {initMORESEGMENTOpParms, MORESEGMENTOp, NULL},
    {initMORESEGMENTRSPOpParms, MORESEGMENTRSPOp, NULL},
    {initLMRXOpParms, LMRXOp, NULL},

#ifdef USE_TLV2_EXTCMD
    {initADCCAPTUREOpParms, ADCCAPTUREOp, NULL},
    {initADCCAPTURERSPOpParms, ADCCAPTURERSPOp, NULL},
    {initGENWAVEFORMOpParms, GENWAVEFORMOp, NULL},
    {initGENWAVEFORMRSPOpParms, GENWAVEFORMRSPOp, NULL},
    {initENABLEDFEOpParms, ENABLEDFEOp, NULL},
    {initENABLEDFERSPOpParms, ENABLEDFERSPOp, NULL},
    {initCALCALTIMEOpParms, CALCALTIMEOp, NULL},
    {initCALCALTIMERSPOpParms, CALCALTIMERSPOp, NULL},
    {initRXDCOGROUPOpParms, RXDCOGROUPOp, NULL},
    {initRXDCOGROUPRSPOpParms, RXDCOGROUPRSPOp, NULL},
#else
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
    {NULL, NULL, NULL},
#endif
    {NULL, NULL, NULL},
    {initLMCHANNELLISTOpParms, LMCHANNELLISTOp, NULL},
    {initLMCHANNELLISTRSPOpParms, LMCHANNELLISTRSPOp, NULL},
    {initLMTXINITOpParms, LMTXINITOp, NULL},
    {initLMTXINITRSPOpParms, LMTXINITRSPOp, NULL},
    {initLMGOOpParms, LMGOOp, NULL},
    {initLMGORSPOpParms, LMGORSPOp, NULL},
    {initLMQUERYOpParms, LMQUERYOp, NULL},
    {initLMQUERYRSPOpParms, LMQUERYRSPOp, NULL},
    {initGENERICUTFCMDOpParms, GENERICUTFCMDOp, NULL},
    {initGENERICUTFCMDRSPOpParms, GENERICUTFCMDRSPOp, NULL},
    {initLMRXINITOpParms, LMRXINITOp, NULL},
    {initLMRXINITRSPOpParms, LMRXINITRSPOp, NULL},
    {initNOISEFLOORREADOpParms, NOISEFLOORREADOp, NULL},
    {initNOISEFLOORREADRSPOpParms, NOISEFLOORREADRSPOp, NULL},
//auto-updated marker - this line should be the last in the table (DON'T REMOVE THIS LINE)	
};

A_UINT32 MaxCmdHandlers = sizeof(CmdHandlerTbl) / sizeof(CMD_HANDLER_ENTRY);


