
//-----------------------------------------------------------------------------
// Qualcomm Proprietary
// Copyright (c) 2015 Qualcomm Atheros, Inc.
// All rights reserved.
// Qualcomm Atheros Confidential and Proprietary.
//
//
// All data and information contained in or disclosed by this document
// are confidential and proprietary information of Qualcomm Atheros, Inc.
// and all rights therein are expressly reserved. By accepting this
// material, the recipient agrees that this material and the information
// contained therein are held in confidence and in trust and will not be
// used, copied, reproduced in whole or in part, nor its contents
// revealed in any manner to others without the express written
// permission of Qualcomm Atheros, Inc.
//
// This technology was exported from the United States in accordance with
// the Export Administration Regulations. Diversion contrary to U.S. law
// prohibited.
//-----------------------------------------------------------------------------


/**
 * Generated file ... Do not hand edit ...
 */

#ifndef _TLV_TAG_DEF_
#define _TLV_TAG_DEF_

typedef enum {

  WIFI_TLV_BASE                            =   0 /* 0x0 */,
  WIFI_TX_PHY_DESC                         =   1 /* 0x1 */,
  WIFI_L_SIG_A                             =   2 /* 0x2 */,
  WIFI_L_SIG_B                             =   3 /* 0x3 */,
  WIFI_HT_SIG                              =   4 /* 0x4 */,
  WIFI_VHT_SIG_A                           =   5 /* 0x5 */,
  WIFI_VHT_SIG_B_SU20                      =   6 /* 0x6 */,
  WIFI_VHT_SIG_B_SU40                      =   7 /* 0x7 */,
  WIFI_VHT_SIG_B_SU80                      =   8 /* 0x8 */,
  WIFI_VHT_SIG_B_MU20                      =   9 /* 0x9 */,
  WIFI_VHT_SIG_B_MU40                      =  10 /* 0xa */,
  WIFI_VHT_SIG_B_MU80                      =  11 /* 0xb */,
  WIFI_TX_SERVICE                          =  12 /* 0xc */,
  WIFI_RX_SERVICE                          =  13 /* 0xd */,
  WIFI_PKT_USER0                           =  14 /* 0xe */,
  WIFI_PKT_USER1                           =  15 /* 0xf */,
  WIFI_PKT_USER2                           =  16 /* 0x10 */,
  WIFI_PKT_USER3                           =  17 /* 0x11 */,
  WIFI_VHT_SIG_B_SU160                     =  18 /* 0x12 */,
  WIFI_VHT_SIG_B_MU160                     =  19 /* 0x13 */,
  WIFI_MAC_PKT_END                         =  32 /* 0x20 */,
  WIFI_TX_PKT_END                          =  33 /* 0x21 */,
  WIFI_RX_PKT_END                          =  34 /* 0x22 */,
  WIFI_TX_LOCATION_REQ                     =  35 /* 0x23 */,
  WIFI_REQ_IMPLICIT_FB                     =  36 /* 0x24 */,
  WIFI_PHY_OFF                             =  37 /* 0x25 */,
  WIFI_RX_PHY_ON                           =  38 /* 0x26 */,
  WIFI_RX_PHY_NAP                          =  39 /* 0x27 */,
  WIFI_RX_CHAIN_MASK                       =  40 /* 0x28 */,
  WIFI_TX_EXPECT_NDP                       =  41 /* 0x29 */,
  WIFI_TX_EXPECT_CBF                       =  42 /* 0x2a */,
  WIFI_TX_CBF_OFFSET                       =  43 /* 0x2b */,
  WIFI_TX_BF_PARAMS                        =  44 /* 0x2c */,
  WIFI_TX_MAC_TIMEOUT                      =  45 /* 0x2d */,
  WIFI_SVD_READY                           =  46 /* 0x2e */,
  WIFI_TX_FREEZE_CAPTURE_CHANNEL           =  47 /* 0x2f */,
  WIFI_TX_FLOW_CONTROL                     =  48 /* 0x30 */,
  WIFI_TLV_ABORT                           =  49 /* 0x31 */,
  WIFI_TLV_TERMINATE                       =  50 /* 0x32 */,
  WIFI_VECTOR_TRANSFER_START               =  51 /* 0x33 */,
  WIFI_VECTOR_FRAGMENT                     =  52 /* 0x34 */,
  WIFI_BT_ANTENNA                          =  53 /* 0x35 */,
  WIFI_MPDU_LINK                           =  54 /* 0x36 */,
  WIFI_MPDU_QUEUE_EXT_COMMON               =  55 /* 0x37 */,
  WIFI_MPDU_QUEUE_EXT_RETRY                =  56 /* 0x38 */,
  WIFI_MPDU_QUEUE_EXT                      =  57 /* 0x39 */,
  WIFI_MPDU_QUEUE                          =  58 /* 0x3a */,
  WIFI_MSDU_LINK_EXT                       =  59 /* 0x3b */,
  WIFI_MSDU_LINK                           =  60 /* 0x3c */,
  WIFI_MSDU_RELEASE                        =  61 /* 0x3d */,
  WIFI_PS_POLL_RESPONSE                    =  62 /* 0x3e */,
  WIFI_QBOOST_RESPONSE                     =  63 /* 0x3f */,
  WIFI_RATE_TABLE_COM_DESC                 =  64 /* 0x40 */,
  WIFI_RATE_TABLE_ENTRY                    =  65 /* 0x41 */,
  WIFI_RATE_TABLE                          =  66 /* 0x42 */,
  WIFI_SCH_RESPONSE_TABLE_ENTRY            =  67 /* 0x43 */,
  WIFI_TX_DATA_USERX                       =  68 /* 0x44 */,
  WIFI_TX_MPDU_START_USERX                 =  69 /* 0x45 */,
  WIFI_TX_RATE_SETTING                     =  70 /* 0x46 */,
  WIFI_UAPSD_RESPONSE                      =  71 /* 0x47 */,
  WIFI_VHT_SIG_B_MAC_SU40                  =  72 /* 0x48 */,
  WIFI_VHT_SIG_B_MAC_SU80                  =  73 /* 0x49 */,
  WIFI_DELETE_HEAD_FRAME                   =  74 /* 0x4a */,
  WIFI_DUMMY                               =  75 /* 0x4b */,
  WIFI_GET_MPDU_QUEUE_HEAD_INFO            =  76 /* 0x4c */,
  WIFI_MPDU_LENGTH                         =  77 /* 0x4d */,
  WIFI_MPDU_LENGTH_USER0                   =  78 /* 0x4e */,
  WIFI_MPDU_LENGTH_USER1                   =  79 /* 0x4f */,
  WIFI_MPDU_LENGTH_USER2                   =  80 /* 0x50 */,
  WIFI_MPDU_LIMIT_STATUS                   =  81 /* 0x51 */,
  WIFI_MPDU_QUEUE_HEAD_INFO                =  82 /* 0x52 */,
  WIFI_MPROT_SS_11B_INFO                   =  83 /* 0x53 */,
  WIFI_MPROT_SS_11N_INFO                   =  84 /* 0x54 */,
  WIFI_MPROT_SS_11A_INFO                   =  85 /* 0x55 */,
  WIFI_MPROT_SS_11AC_SU_INFO               =  86 /* 0x56 */,
  WIFI_OLE_BUF_STATUS                      =  87 /* 0x57 */,
  WIFI_PCU_BUF_STATUS                      =  88 /* 0x58 */,
  WIFI_PDG_BYPASS                          =  89 /* 0x59 */,
  WIFI_PDG_FES_SETUP                       =  90 /* 0x5a */,
  WIFI_PDG_RESPONSE                        =  91 /* 0x5b */,
  WIFI_PDG_SETUP_USERX                     =  92 /* 0x5c */,
  WIFI_PDG_SETUP_USER0                     =  93 /* 0x5d */,
  WIFI_PDG_SETUP_USER1                     =  94 /* 0x5e */,
  WIFI_PDG_SETUP_USER2                     =  95 /* 0x5f */,
  WIFI_VHT_SIG_B_MAC_SU160                 =  96 /* 0x60 */,
  WIFI_PEER_ENTRY                          =  99 /* 0x63 */,
  WIFI_PEER_ENTRY_USER0                    = 100 /* 0x64 */,
  WIFI_PEER_ENTRY_USER1                    = 101 /* 0x65 */,
  WIFI_PEER_ENTRY_USER2                    = 102 /* 0x66 */,
  WIFI_PPDU_SS_11B_INFO                    = 103 /* 0x67 */,
  WIFI_PPDU_SS_11N_INFO                    = 104 /* 0x68 */,
  WIFI_PPDU_SS_11A_INFO                    = 105 /* 0x69 */,
  WIFI_PPDU_SS_11AC_SU_INFO                = 106 /* 0x6a */,
  WIFI_PPDU_SS_11AC_MU_INFO                = 107 /* 0x6b */,
  WIFI_PPDU_TX_PHY_DESC                    = 108 /* 0x6c */,
  WIFI_MPROT_TX_PHY_DESC                   = 109 /* 0x6d */,
  WIFI_QM_PDG_START                        = 110 /* 0x6e */,
  WIFI_QUEUE_EXT_REF0                      = 111 /* 0x6f */,
  WIFI_QUEUE_EXT_REF1                      = 112 /* 0x70 */,
  WIFI_QUEUE_EXT_REF2                      = 113 /* 0x71 */,
  WIFI_QUEUE_EXT_USER0                     = 114 /* 0x72 */,
  WIFI_QUEUE_EXT_USER1                     = 115 /* 0x73 */,
  WIFI_QUEUE_EXT_USER2                     = 116 /* 0x74 */,
  WIFI_QUEUE_NOT_EMPTY                     = 117 /* 0x75 */,
  WIFI_QUEUE_PAUSE_STATUS                  = 118 /* 0x76 */,
  WIFI_RATE_TABLE_REF0                     = 119 /* 0x77 */,
  WIFI_RATE_TABLE_REF1                     = 120 /* 0x78 */,
  WIFI_RATE_TABLE_REF2                     = 121 /* 0x79 */,
  WIFI_SCHEDULER_TLV                       = 122 /* 0x7a */,
  WIFI_SCHEDULER_TRANSMIT_STATUS           = 123 /* 0x7b */,
  WIFI_SCH_RX_FRAME_INFO                   = 124 /* 0x7c */,
  WIFI_TX_BUFFERS_SETUP                    = 125 /* 0x7d */,
  WIFI_TX_CV_START_REF0                    = 126 /* 0x7e */,
  WIFI_TX_CV_START_REF1                    = 127 /* 0x7f */,
  WIFI_TX_CV_START_REF2                    = 128 /* 0x80 */,
  WIFI_TX_DATA_USER0                       = 129 /* 0x81 */,
  WIFI_TX_DATA_USER1                       = 130 /* 0x82 */,
  WIFI_TX_DATA_USER2                       = 131 /* 0x83 */,
  WIFI_TX_FES_SETUP_COMPLETE               = 132 /* 0x84 */,
  WIFI_TX_FES_SETUP                        = 133 /* 0x85 */,
  WIFI_TX_FES_STATUS                       = 134 /* 0x86 */,
  WIFI_TX_FLUSH                            = 135 /* 0x87 */,
  WIFI_TX_MPDU_END_USER0                   = 136 /* 0x88 */,
  WIFI_TX_MPDU_END_USER1                   = 137 /* 0x89 */,
  WIFI_TX_MPDU_END_USER2                   = 138 /* 0x8a */,
  WIFI_TX_MPDU_START_USER0                 = 139 /* 0x8b */,
  WIFI_TX_MPDU_START_USER1                 = 140 /* 0x8c */,
  WIFI_TX_MPDU_START_USER2                 = 141 /* 0x8d */,
  WIFI_TX_MSDU_END_USER0                   = 142 /* 0x8e */,
  WIFI_TX_MSDU_END_USER1                   = 143 /* 0x8f */,
  WIFI_TX_MSDU_END_USER2                   = 144 /* 0x90 */,
  WIFI_TX_MSDU_START_USER0                 = 145 /* 0x91 */,
  WIFI_TX_MSDU_START_USER1                 = 146 /* 0x92 */,
  WIFI_TX_MSDU_START_USER2                 = 147 /* 0x93 */,
  WIFI_RX_RSSI_LEGACY                      = 148 /* 0x94 */,
  WIFI_RX_RSSI_HT                          = 149 /* 0x95 */,
  WIFI_RX_EVM                              = 150 /* 0x96 */,
  WIFI_RX_TIMING_OFFSET                    = 151 /* 0x97 */,
  WIFI_RX_PHY_PPDU_END                     = 152 /* 0x98 */,
  WIFI_SCHEDULER_CMD                       = 153 /* 0x99 */,
  WIFI_TX_CV_START_REFX                    = 154 /* 0x9a */,
  WIFI_TX_CV_START                         = 155 /* 0x9b */,
  WIFI_TX_CV_START_USER0                   = 156 /* 0x9c */,
  WIFI_TX_CV_START_USER1                   = 157 /* 0x9d */,
  WIFI_TX_CV_START_USER2                   = 158 /* 0x9e */,
  WIFI_TX_CV_DATA                          = 159 /* 0x9f */,
  WIFI_TX_CV_DATA_USER0                    = 160 /* 0xa0 */,
  WIFI_TX_CV_DATA_USER1                    = 161 /* 0xa1 */,
  WIFI_TX_CV_DATA_USER2                    = 162 /* 0xa2 */,
  WIFI_QUEUE_HEAD                          = 163 /* 0xa3 */,
  WIFI_QUEUE_HEAD_USER0                    = 164 /* 0xa4 */,
  WIFI_QUEUE_HEAD_USER1                    = 165 /* 0xa5 */,
  WIFI_QUEUE_HEAD_USER2                    = 166 /* 0xa6 */,
  WIFI_PCU_PPDU_SETUP                      = 167 /* 0xa7 */,
  WIFI_PRE_TX_PHY_DESC                     = 168 /* 0xa8 */,
  WIFI_VHT_SIG_B_MAC_MU40                  = 169 /* 0xa9 */,
  WIFI_VHT_SIG_B_MAC_MU80                  = 170 /* 0xaa */,
  WIFI_TX_PCU_INFO                         = 171 /* 0xab */,
  WIFI_TX_MSDU_START_USERX                 = 172 /* 0xac */,
  WIFI_TX_FRAME_INFO                       = 173 /* 0xad */,
  WIFI_TX_FLUSH_REQ                        = 174 /* 0xae */,
  WIFI_RX_PPDU_START                       = 175 /* 0xaf */,
  WIFI_RX_PPDU_END                         = 176 /* 0xb0 */,
  WIFI_RX_MPDU_START                       = 177 /* 0xb1 */,
  WIFI_RX_MPDU_PCU_START                   = 178 /* 0xb2 */,
  WIFI_RX_MPDU_END                         = 179 /* 0xb3 */,
  WIFI_RX_MSDU_START                       = 180 /* 0xb4 */,
  WIFI_RX_MSDU_END                         = 181 /* 0xb5 */,
  WIFI_RX_ATTENTION                        = 182 /* 0xb6 */,
  WIFI_RX_FRAG_INFO                        = 183 /* 0xb7 */,
  WIFI_RX_HEADER                           = 184 /* 0xb8 */,
  WIFI_RX_PACKET                           = 185 /* 0xb9 */,
  WIFI_RX_PEER_ENTRY                       = 186 /* 0xba */,
  WIFI_TX_CBF_INFO                         = 187 /* 0xbb */,
  WIFI_RX_FRAME_INFO                       = 188 /* 0xbc */,
  WIFI_RX_RESP                             = 189 /* 0xbd */,
  WIFI_RX_MESSAGE                          = 190 /* 0xbe */,
  WIFI_ADDR_SEARCH_ENTRY                   = 191 /* 0xbf */,
  WIFI_CV_LENGTH                           = 192 /* 0xc0 */,
  WIFI_VHT_SIG_B_MAC_MU160                 = 193 /* 0xc1 */,
  WIFI_RX_LOCATION_INFO                    = 240 /* 0xf0 */,
  WIFI_ADD_FRAME_CMD                       = 243 /* 0xf3 */,
  WIFI_DELETE_MPDU_CMD                     = 244 /* 0xf4 */,
  WIFI_FLUSH_QID_CMD                       = 245 /* 0xf5 */,
  WIFI_PAUSE_QID_CMD                       = 246 /* 0xf6 */,
  WIFI_UNPAUSE_QID_CMD                     = 247 /* 0xf7 */,
  WIFI_UPDATE_DESC_CMD                     = 248 /* 0xf8 */

} tlv_tag_def_e; ///< tlv_tag_def Enum Type

#endif // _TLV_TAG_DEF_
