# QCA IPQ Sound Card Support
snd-soc-ipq-objs := ipq.o
snd-soc-ipq-cpu-dai-objs := ipq-cpu-dai.o
snd-soc-ipq-pcm-i2s-objs := ipq-pcm-i2s.o
snd-soc-ipq-pcm-tdm-objs := ipq-pcm-tdm.o
snd-soc-ipq-pcm-spdif-objs := ipq-pcm-spdif.o
snd-soc-ipq-codec-objs := ipq-codec.o
snd-soc-ipq-pcm-raw-objs := ipq-pcm-raw.o ipq-pcm-raw-lb-test.o
snd-soc-ipq806x-pcm-raw-objs := ipq806x-pcm-raw.o ipq806x-pcm-raw-lb-test.o
snd-soc-ipq806x-lpaif-objs := ipq806x-lpaif.o

obj-$(CONFIG_SND_SOC_IPQ) += ipq.o
obj-$(CONFIG_SND_SOC_IPQ_ADSS) += ipq-adss.o
obj-$(CONFIG_SND_SOC_IPQ_CPU_DAI) += snd-soc-ipq-cpu-dai.o
obj-$(CONFIG_SND_SOC_IPQ_STEREO) += ipq-stereo.o
obj-$(CONFIG_SND_SOC_IPQ_MBOX) += ipq-mbox.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_I2S) += snd-soc-ipq-pcm-i2s.o
obj-$(CONFIG_SND_SOC_IPQ_CODEC) += snd-soc-ipq-codec.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_SPDIF) += snd-soc-ipq-pcm-spdif.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_TDM) += snd-soc-ipq-pcm-tdm.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_RAW) += snd-soc-ipq-pcm-raw.o
obj-$(CONFIG_SND_SOC_IPQ806X_PCM_RAW) += snd-soc-ipq806x-pcm-raw.o
obj-$(CONFIG_SND_SOC_IPQ806X_LPAIF) += snd-soc-ipq806x-lpaif.o
