// Copyright (c) 2013 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _OLE_BUF_STATUS_H_
#define _OLE_BUF_STATUS_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//	0	avail_ole_buf_bytes[10:0], buf_delta_words_drained[22:11], cmdfifo_delta_entries_drained[28:23], reserved[31:29]
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_OLE_BUF_STATUS 1

struct ole_buf_status {
    volatile uint32_t avail_ole_buf_bytes             : 11, //[10:0]
                      buf_delta_words_drained         : 12, //[22:11]
                      cmdfifo_delta_entries_drained   :  6, //[28:23]
                      reserved                        :  3; //[31:29]
};

/*

avail_ole_buf_bytes
			
			Number of bytes  available in the ole  buffer
			
			<legal 2047-0>

buf_delta_words_drained
			
			The number of data words removed from  the OLE buffer
			since the last OLE_BUF_STATUS TLV was generated.

cmdfifo_delta_entries_drained
			
			The number of data words removed from  the OLE Command
			FIFO since the last OLE_BUF_STATUS TLV was generated.

reserved
			
			0
*/


/* Description		OLE_BUF_STATUS_0_AVAIL_OLE_BUF_BYTES
			
			Number of bytes  available in the ole  buffer
			
			<legal 2047-0>
*/
#define OLE_BUF_STATUS_0_AVAIL_OLE_BUF_BYTES_OFFSET                  0x00000000
#define OLE_BUF_STATUS_0_AVAIL_OLE_BUF_BYTES_LSB                     0
#define OLE_BUF_STATUS_0_AVAIL_OLE_BUF_BYTES_MASK                    0x000007ff

/* Description		OLE_BUF_STATUS_0_BUF_DELTA_WORDS_DRAINED
			
			The number of data words removed from  the OLE buffer
			since the last OLE_BUF_STATUS TLV was generated.
*/
#define OLE_BUF_STATUS_0_BUF_DELTA_WORDS_DRAINED_OFFSET              0x00000000
#define OLE_BUF_STATUS_0_BUF_DELTA_WORDS_DRAINED_LSB                 11
#define OLE_BUF_STATUS_0_BUF_DELTA_WORDS_DRAINED_MASK                0x007ff800

/* Description		OLE_BUF_STATUS_0_CMDFIFO_DELTA_ENTRIES_DRAINED
			
			The number of data words removed from  the OLE Command
			FIFO since the last OLE_BUF_STATUS TLV was generated.
*/
#define OLE_BUF_STATUS_0_CMDFIFO_DELTA_ENTRIES_DRAINED_OFFSET        0x00000000
#define OLE_BUF_STATUS_0_CMDFIFO_DELTA_ENTRIES_DRAINED_LSB           23
#define OLE_BUF_STATUS_0_CMDFIFO_DELTA_ENTRIES_DRAINED_MASK          0x1f800000

/* Description		OLE_BUF_STATUS_0_RESERVED
			
			0
*/
#define OLE_BUF_STATUS_0_RESERVED_OFFSET                             0x00000000
#define OLE_BUF_STATUS_0_RESERVED_LSB                                29
#define OLE_BUF_STATUS_0_RESERVED_MASK                               0xe0000000


#endif // _OLE_BUF_STATUS_H_
