// Copyright (c) 2013 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _TX_CV_START_USER2_H_
#define _TX_CV_START_USER2_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//	0-1	struct tx_cv_start tx_cv_start_user_2;
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_TX_CV_START_USER2 2

struct tx_cv_start_user2 {
    struct            tx_cv_start                       tx_cv_start_user_2;
};

/*

struct tx_cv_start tx_cv_start_user_2
			
			See definition of TX_CV_START
*/

#define TX_CV_START_USER2_0_TX_CV_START_TX_CV_START_USER_2_OFFSET    0x00000000
#define TX_CV_START_USER2_0_TX_CV_START_TX_CV_START_USER_2_LSB       0
#define TX_CV_START_USER2_0_TX_CV_START_TX_CV_START_USER_2_MASK      0xffffffff
#define TX_CV_START_USER2_1_TX_CV_START_TX_CV_START_USER_2_OFFSET    0x00000004
#define TX_CV_START_USER2_1_TX_CV_START_TX_CV_START_USER_2_LSB       0
#define TX_CV_START_USER2_1_TX_CV_START_TX_CV_START_USER_2_MASK      0xffffffff


#endif // _TX_CV_START_USER2_H_
