// Copyright (c) 2013 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _QUEUE_HEAD_USER0_H_
#define _QUEUE_HEAD_USER0_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//	0	struct queue_head queue_head_user0;
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_QUEUE_HEAD_USER0 1

struct queue_head_user0 {
    struct            queue_head                       queue_head_user0;
};

/*

struct queue_head queue_head_user0
			
			See description of QUEUE_HEAD
*/

#define QUEUE_HEAD_USER0_0_QUEUE_HEAD_QUEUE_HEAD_USER0_OFFSET        0x00000000
#define QUEUE_HEAD_USER0_0_QUEUE_HEAD_QUEUE_HEAD_USER0_LSB           0
#define QUEUE_HEAD_USER0_0_QUEUE_HEAD_QUEUE_HEAD_USER0_MASK          0xffffffff


#endif // _QUEUE_HEAD_USER0_H_
