/*
 * Copyright (c) 2017, The Linux Foundation. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _DT_BINDINGS_CLOCK_QCA_ADSS_IPQ807x_H
#define _DT_BINDINGS_CLOCK_QCA_ADSS_IPQ807x_H

#define ADSS_AUDIO_RXM_CLK_SRC					0
#define ADSS_AUDIO_RXM_POSTDIV_CLK_SRC				1
#define ADSS_AUDIO_RXM_CLK					2
#define ADSS_AUDIO_RXB_POSTDIV_CLK_SRC				3
#define ADSS_AUDIO_RXB_CLK					4
#define ADSS_AUDIO_TXM_CLK_SRC					5
#define ADSS_AUDIO_TXM_POSTDIV_CLK_SRC				6
#define ADSS_AUDIO_TXM_CLK					7
#define ADSS_AUDIO_TXB_POSTDIV_CLK_SRC				8
#define ADSS_AUDIO_TXB_CLK					9
#define ADSS_AUDIO_PCM_CLK_SRC					10
#define ADSS_AUDIO_PCM_POSTDIV_CLK_SRC				11
#define ADSS_AUDIO_PCM_CLK					12
#define ADSS_AUDIO_XO_CLK					13
#define ADSS_AUDIO_AHB_CLK					14
#define ADSS_AUDIO_I2S0_CLK					15
#define ADSS_AUDIO_I2S3_CLK					16
#define ADSS_AUDIO_MBOX0_CLK					17
#define ADSS_AUDIO_MBOX3_CLK					18
#define ADSS_AUDIO_RXB_CLK_MUX					19
#define ADSS_AUDIO_TXB_CLK_MUX					20

#endif
