/*
 * Copyright (c) 2014, The Linux Foundation. All rights reserved.
 * Permission to use, copy, modify, and/or distribute this software for
 * any purpose with or without fee is hereby granted, provided that the
 * above copyright notice and this permission notice appear in all copies.
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
 * OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _NSS_MACSEC_REGISTER_H_
#define _NSS_MACSEC_REGISTER_H_

/*[register] IGSY_L2SEC_VERSION*/
#define IGSY_L2SEC_VERSION
#define IGSY_L2SEC_VERSION_ADDRESS 0x0
#define IGSY_L2SEC_VERSION_NUM     1
#define IGSY_L2SEC_VERSION_INC     0x4
#define IGSY_L2SEC_VERSION_TYPE    REG_TYPE_RO
#define IGSY_L2SEC_VERSION_DEFAULT 0x0

/*[register] INSY_PRESCALE*/
#define INSY_PRESCALE
#define INSY_PRESCALE_ADDRESS 0x8
#define INSY_PRESCALE_NUM     1
#define INSY_PRESCALE_INC     0x4
#define INSY_PRESCALE_TYPE    REG_TYPE_RW
#define INSY_PRESCALE_DEFAULT 0x0

/*[register] CSR_IGSY_VLAN_TPID0*/
#define CSR_IGSY_VLAN_TPID0
#define CSR_IGSY_VLAN_TPID0_ADDRESS 0xc
#define CSR_IGSY_VLAN_TPID0_NUM     1
#define CSR_IGSY_VLAN_TPID0_INC     0x4
#define CSR_IGSY_VLAN_TPID0_TYPE    REG_TYPE_RW
#define CSR_IGSY_VLAN_TPID0_DEFAULT 0x0

/*[register] CSR_IGSY_VLAN_TPID1*/
#define CSR_IGSY_VLAN_TPID1
#define CSR_IGSY_VLAN_TPID1_ADDRESS 0x10
#define CSR_IGSY_VLAN_TPID1_NUM     1
#define CSR_IGSY_VLAN_TPID1_INC     0x4
#define CSR_IGSY_VLAN_TPID1_TYPE    REG_TYPE_RW
#define CSR_IGSY_VLAN_TPID1_DEFAULT 0x0

/*[register] CSR_IGSY_VLAN_CP_TAG*/
#define CSR_IGSY_VLAN_CP_TAG
#define CSR_IGSY_VLAN_CP_TAG_ADDRESS 0x14
#define CSR_IGSY_VLAN_CP_TAG_NUM     1
#define CSR_IGSY_VLAN_CP_TAG_INC     0x4
#define CSR_IGSY_VLAN_CP_TAG_TYPE    REG_TYPE_RW
#define CSR_IGSY_VLAN_CP_TAG_DEFAULT 0x0

/*[register] CSR_IGSY_MTU*/
#define CSR_IGSY_MTU
#define CSR_IGSY_MTU_ADDRESS 0x18
#define CSR_IGSY_MTU_NUM     1
#define CSR_IGSY_MTU_INC     0x4
#define CSR_IGSY_MTU_TYPE    REG_TYPE_RW
#define CSR_IGSY_MTU_DEFAULT 0x0

/*[register] CSR_IGSY_CTRL*/
#define CSR_IGSY_CTRL
#define CSR_IGSY_CTRL_ADDRESS 0x1c
#define CSR_IGSY_CTRL_NUM     1
#define CSR_IGSY_CTRL_INC     0x4
#define CSR_IGSY_CTRL_TYPE    REG_TYPE_RW
#define CSR_IGSY_CTRL_DEFAULT 0x0

/*[register] CSR_INSY_SA_THR*/
#define CSR_INSY_SA_THR
#define CSR_INSY_SA_THR_ADDRESS 0x20
#define CSR_INSY_SA_THR_NUM     1
#define CSR_INSY_SA_THR_INC     0x4
#define CSR_INSY_SA_THR_TYPE    REG_TYPE_RW
#define CSR_INSY_SA_THR_DEFAULT 0x0

/*[register] INSY_FMT_CSR_DEBUG*/
#define INSY_FMT_CSR_DEBUG
#define INSY_FMT_CSR_DEBUG_ADDRESS 0x24
#define INSY_FMT_CSR_DEBUG_NUM     1
#define INSY_FMT_CSR_DEBUG_INC     0x4
#define INSY_FMT_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_FMT_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_RPY_CSR_DEBUG*/
#define INSY_RPY_CSR_DEBUG
#define INSY_RPY_CSR_DEBUG_ADDRESS 0x28
#define INSY_RPY_CSR_DEBUG_NUM     1
#define INSY_RPY_CSR_DEBUG_INC     0x4
#define INSY_RPY_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_RPY_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG*/
#define INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG
#define INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_ADDRESS 0x2c
#define INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_NUM     1
#define INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_INC     0x4
#define INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_GCM_MULT_DATA_CNT_CSR_DEBUG*/
#define INSY_GCM_MULT_DATA_CNT_CSR_DEBUG
#define INSY_GCM_MULT_DATA_CNT_CSR_DEBUG_ADDRESS 0x30
#define INSY_GCM_MULT_DATA_CNT_CSR_DEBUG_NUM     1
#define INSY_GCM_MULT_DATA_CNT_CSR_DEBUG_INC     0x4
#define INSY_GCM_MULT_DATA_CNT_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_GCM_MULT_DATA_CNT_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_GCM_MULT_LENA_LSB_CSR_DEBUG*/
#define INSY_GCM_MULT_LENA_LSB_CSR_DEBUG
#define INSY_GCM_MULT_LENA_LSB_CSR_DEBUG_ADDRESS 0x34
#define INSY_GCM_MULT_LENA_LSB_CSR_DEBUG_NUM     1
#define INSY_GCM_MULT_LENA_LSB_CSR_DEBUG_INC     0x4
#define INSY_GCM_MULT_LENA_LSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_GCM_MULT_LENA_LSB_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_GCM_MULT_LENA_MSB_CSR_DEBUG*/
#define INSY_GCM_MULT_LENA_MSB_CSR_DEBUG
#define INSY_GCM_MULT_LENA_MSB_CSR_DEBUG_ADDRESS 0x38
#define INSY_GCM_MULT_LENA_MSB_CSR_DEBUG_NUM     1
#define INSY_GCM_MULT_LENA_MSB_CSR_DEBUG_INC     0x4
#define INSY_GCM_MULT_LENA_MSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_GCM_MULT_LENA_MSB_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_GCM_MULT_LENC_LSB_CSR_DEBUG*/
#define INSY_GCM_MULT_LENC_LSB_CSR_DEBUG
#define INSY_GCM_MULT_LENC_LSB_CSR_DEBUG_ADDRESS 0x3c
#define INSY_GCM_MULT_LENC_LSB_CSR_DEBUG_NUM     1
#define INSY_GCM_MULT_LENC_LSB_CSR_DEBUG_INC     0x4
#define INSY_GCM_MULT_LENC_LSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_GCM_MULT_LENC_LSB_CSR_DEBUG_DEFAULT 0x0

/*[register] INSY_GCM_MULT_LENC_MSB_CSR_DEBUG*/
#define INSY_GCM_MULT_LENC_MSB_CSR_DEBUG
#define INSY_GCM_MULT_LENC_MSB_CSR_DEBUG_ADDRESS 0x40
#define INSY_GCM_MULT_LENC_MSB_CSR_DEBUG_NUM     1
#define INSY_GCM_MULT_LENC_MSB_CSR_DEBUG_INC     0x4
#define INSY_GCM_MULT_LENC_MSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define INSY_GCM_MULT_LENC_MSB_CSR_DEBUG_DEFAULT 0x0

/*[register] IGSY_CSR_BUSY_SIGNAL*/
#define IGSY_CSR_BUSY_SIGNAL
#define IGSY_CSR_BUSY_SIGNAL_ADDRESS 0x44
#define IGSY_CSR_BUSY_SIGNAL_NUM     1
#define IGSY_CSR_BUSY_SIGNAL_INC     0x4
#define IGSY_CSR_BUSY_SIGNAL_TYPE    REG_TYPE_RO
#define IGSY_CSR_BUSY_SIGNAL_DEFAULT 0x0

/*[register] INSY_SCTRL_DROP_EN*/
#define INSY_SCTRL_DROP_EN
#define INSY_SCTRL_DROP_EN_ADDRESS 0x48
#define INSY_SCTRL_DROP_EN_NUM     1
#define INSY_SCTRL_DROP_EN_INC     0x4
#define INSY_SCTRL_DROP_EN_TYPE    REG_TYPE_RW
#define INSY_SCTRL_DROP_EN_DEFAULT 0x0

/*[register] INSY_ECTRL_EN*/
#define INSY_ECTRL_EN
#define INSY_ECTRL_EN_ADDRESS 0x4c
#define INSY_ECTRL_EN_NUM     1
#define INSY_ECTRL_EN_INC     0x4
#define INSY_ECTRL_EN_TYPE    REG_TYPE_RW
#define INSY_ECTRL_EN_DEFAULT 0x0

/*[register] INSY_EMAC_REGS*/
#define INSY_EMAC_REGS
#define INSY_EMAC_REGS_ADDRESS 0x50
#define INSY_EMAC_REGS_NUM     1
#define INSY_EMAC_REGS_INC     0x4
#define INSY_EMAC_REGS_TYPE    REG_TYPE_RW
#define INSY_EMAC_REGS_DEFAULT 0x0

/*[register] INSY_SCI_DEFAULT_ENTRY_LSB*/
#define INSY_SCI_DEFAULT_ENTRY_LSB
#define INSY_SCI_DEFAULT_ENTRY_LSB_ADDRESS 0x54
#define INSY_SCI_DEFAULT_ENTRY_LSB_NUM     1
#define INSY_SCI_DEFAULT_ENTRY_LSB_INC     0x4
#define INSY_SCI_DEFAULT_ENTRY_LSB_TYPE    REG_TYPE_RW
#define INSY_SCI_DEFAULT_ENTRY_LSB_DEFAULT 0x0

/*[register] INSY_SCI_DEFAULT_ENTRY_MSB*/
#define INSY_SCI_DEFAULT_ENTRY_MSB
#define INSY_SCI_DEFAULT_ENTRY_MSB_ADDRESS 0x58
#define INSY_SCI_DEFAULT_ENTRY_MSB_NUM     1
#define INSY_SCI_DEFAULT_ENTRY_MSB_INC     0x4
#define INSY_SCI_DEFAULT_ENTRY_MSB_TYPE    REG_TYPE_RW
#define INSY_SCI_DEFAULT_ENTRY_MSB_DEFAULT 0x0

/*[register] IGSY_INT*/
#define IGSY_INT
#define IGSY_INT_ADDRESS 0x5c
#define IGSY_INT_NUM     1
#define IGSY_INT_INC     0x4
#define IGSY_INT_TYPE    REG_TYPE_RW
#define IGSY_INT_DEFAULT 0x0

/*[register] IGSY_INT_EN*/
#define IGSY_INT_EN
#define IGSY_INT_EN_ADDRESS 0x60
#define IGSY_INT_EN_NUM     1
#define IGSY_INT_EN_INC     0x4
#define IGSY_INT_EN_TYPE    REG_TYPE_RW
#define IGSY_INT_EN_DEFAULT 0x0

/*[register] ICV_ERR_REG*/
#define ICV_ERR_REG
#define ICV_ERR_REG_ADDRESS 0x64
#define ICV_ERR_REG_NUM     1
#define ICV_ERR_REG_INC     0x4
#define ICV_ERR_REG_TYPE    REG_TYPE_RW
#define ICV_ERR_REG_DEFAULT 0x0

/*[register] RPY_ERR_REG*/
#define RPY_ERR_REG
#define RPY_ERR_REG_ADDRESS 0x68
#define RPY_ERR_REG_NUM     1
#define RPY_ERR_REG_INC     0x4
#define RPY_ERR_REG_TYPE    REG_TYPE_RW
#define RPY_ERR_REG_DEFAULT 0x0

/*[register] IGSY_SA_EXP*/
#define IGSY_SA_EXP
#define IGSY_SA_EXP_ADDRESS 0x6c
#define IGSY_SA_EXP_NUM     1
#define IGSY_SA_EXP_INC     0x4
#define IGSY_SA_EXP_TYPE    REG_TYPE_RW
#define IGSY_SA_EXP_DEFAULT 0x0

/*[register] IGSY_SA_THR*/
#define IGSY_SA_THR
#define IGSY_SA_THR_ADDRESS 0x70
#define IGSY_SA_THR_NUM     1
#define IGSY_SA_THR_INC     0x4
#define IGSY_SA_THR_TYPE    REG_TYPE_RW
#define IGSY_SA_THR_DEFAULT 0x0

/*[register] IGECC_ERR_REG*/
#define IGECC_ERR_REG
#define IGECC_ERR_REG_ADDRESS 0x74
#define IGECC_ERR_REG_NUM     1
#define IGECC_ERR_REG_INC     0x4
#define IGECC_ERR_REG_TYPE    REG_TYPE_RW
#define IGECC_ERR_REG_DEFAULT 0x0

/*[register] IGPRC_ECC_ERR1_ADDR*/
#define IGPRC_ECC_ERR1_ADDR
#define IGPRC_ECC_ERR1_ADDR_ADDRESS 0x78
#define IGPRC_ECC_ERR1_ADDR_NUM     1
#define IGPRC_ECC_ERR1_ADDR_INC     0x4
#define IGPRC_ECC_ERR1_ADDR_TYPE    REG_TYPE_RW
#define IGPRC_ECC_ERR1_ADDR_DEFAULT 0x0

/*[register] IGPRC_ECC_ERR2_ADDR*/
#define IGPRC_ECC_ERR2_ADDR
#define IGPRC_ECC_ERR2_ADDR_ADDRESS 0x7c
#define IGPRC_ECC_ERR2_ADDR_NUM     1
#define IGPRC_ECC_ERR2_ADDR_INC     0x4
#define IGPRC_ECC_ERR2_ADDR_TYPE    REG_TYPE_RW
#define IGPRC_ECC_ERR2_ADDR_DEFAULT 0x0

/*[register] IGLKUP_CTLF_ECC_ERR_ADDR*/
#define IGLKUP_CTLF_ECC_ERR_ADDR
#define IGLKUP_CTLF_ECC_ERR_ADDR_ADDRESS 0x80
#define IGLKUP_CTLF_ECC_ERR_ADDR_NUM     1
#define IGLKUP_CTLF_ECC_ERR_ADDR_INC     0x4
#define IGLKUP_CTLF_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define IGLKUP_CTLF_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] PFMT_ECC_ERR_ADDR*/
#define PFMT_ECC_ERR_ADDR
#define PFMT_ECC_ERR_ADDR_ADDRESS 0x84
#define PFMT_ECC_ERR_ADDR_NUM     1
#define PFMT_ECC_ERR_ADDR_INC     0x4
#define PFMT_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define PFMT_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] IRPY_SC_SA_ECC_ERR_ADDR*/
#define IRPY_SC_SA_ECC_ERR_ADDR
#define IRPY_SC_SA_ECC_ERR_ADDR_ADDRESS 0x88
#define IRPY_SC_SA_ECC_ERR_ADDR_NUM     1
#define IRPY_SC_SA_ECC_ERR_ADDR_INC     0x4
#define IRPY_SC_SA_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define IRPY_SC_SA_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] IGPOC_CTLF_ECC_ERR_ADDR*/
#define IGPOC_CTLF_ECC_ERR_ADDR
#define IGPOC_CTLF_ECC_ERR_ADDR_ADDRESS 0x8c
#define IGPOC_CTLF_ECC_ERR_ADDR_NUM     1
#define IGPOC_CTLF_ECC_ERR_ADDR_INC     0x4
#define IGPOC_CTLF_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define IGPOC_CTLF_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] IGPOC_ECC_ERR1_ADDR*/
#define IGPOC_ECC_ERR1_ADDR
#define IGPOC_ECC_ERR1_ADDR_ADDRESS 0x90
#define IGPOC_ECC_ERR1_ADDR_NUM     1
#define IGPOC_ECC_ERR1_ADDR_INC     0x4
#define IGPOC_ECC_ERR1_ADDR_TYPE    REG_TYPE_RW
#define IGPOC_ECC_ERR1_ADDR_DEFAULT 0x0

/*[register] IGPOC_ECC_ERR2_ADDR*/
#define IGPOC_ECC_ERR2_ADDR
#define IGPOC_ECC_ERR2_ADDR_ADDRESS 0x94
#define IGPOC_ECC_ERR2_ADDR_NUM     1
#define IGPOC_ECC_ERR2_ADDR_INC     0x4
#define IGPOC_ECC_ERR2_ADDR_TYPE    REG_TYPE_RW
#define IGPOC_ECC_ERR2_ADDR_DEFAULT 0x0

/*[register] IGSY_SMIB_ECC_ERR_ADDR*/
#define IGSY_SMIB_ECC_ERR_ADDR
#define IGSY_SMIB_ECC_ERR_ADDR_ADDRESS 0x9c
#define IGSY_SMIB_ECC_ERR_ADDR_NUM     1
#define IGSY_SMIB_ECC_ERR_ADDR_INC     0x4
#define IGSY_SMIB_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define IGSY_SMIB_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] IG_TABLE_CMD*/
#define IG_TABLE_CMD
#define IG_TABLE_CMD_ADDRESS 0x100
#define IG_TABLE_CMD_NUM     1
#define IG_TABLE_CMD_INC     0x4
#define IG_TABLE_CMD_TYPE    REG_TYPE_RW
#define IG_TABLE_CMD_DEFAULT 0x0

/*[register] IG_TABLE_DATA*/
#define IG_TABLE_DATA
#define IG_TABLE_DATA_ADDRESS 0x140
#define IG_TABLE_DATA_NUM     1
#define IG_TABLE_DATA_INC     0x40
#define IG_TABLE_DATA_TYPE    REG_TYPE_RW
#define IG_TABLE_DATA_DEFAULT 0x0

/*[register] EGSY_L2SEC_VERSION*/
#define EGSY_L2SEC_VERSION
#define EGSY_L2SEC_VERSION_ADDRESS 0x0
#define EGSY_L2SEC_VERSION_NUM     1
#define EGSY_L2SEC_VERSION_INC     0x4
#define EGSY_L2SEC_VERSION_TYPE    REG_TYPE_RO
#define EGSY_L2SEC_VERSION_DEFAULT 0x0

/*[register] EGSY_L2SEC_CONTROL*/
#define EGSY_L2SEC_CONTROL
#define EGSY_L2SEC_CONTROL_ADDRESS 0x4
#define EGSY_L2SEC_CONTROL_NUM     1
#define EGSY_L2SEC_CONTROL_INC     0x4
#define EGSY_L2SEC_CONTROL_TYPE    REG_TYPE_RW
#define EGSY_L2SEC_CONTROL_DEFAULT 0x0

/*[register] EGSY_PRESCALE*/
#define EGSY_PRESCALE
#define EGSY_PRESCALE_ADDRESS 0x8
#define EGSY_PRESCALE_NUM     1
#define EGSY_PRESCALE_INC     0x4
#define EGSY_PRESCALE_TYPE    REG_TYPE_RW
#define EGSY_PRESCALE_DEFAULT 0x0

/*[register] CSR_EGSY_VLAN_TPID0*/
#define CSR_EGSY_VLAN_TPID0
#define CSR_EGSY_VLAN_TPID0_ADDRESS 0x10
#define CSR_EGSY_VLAN_TPID0_NUM     1
#define CSR_EGSY_VLAN_TPID0_INC     0x4
#define CSR_EGSY_VLAN_TPID0_TYPE    REG_TYPE_RW
#define CSR_EGSY_VLAN_TPID0_DEFAULT 0x0

/*[register] CSR_EGSY_VLAN_TPID1*/
#define CSR_EGSY_VLAN_TPID1
#define CSR_EGSY_VLAN_TPID1_ADDRESS 0x14
#define CSR_EGSY_VLAN_TPID1_NUM     1
#define CSR_EGSY_VLAN_TPID1_INC     0x4
#define CSR_EGSY_VLAN_TPID1_TYPE    REG_TYPE_RW
#define CSR_EGSY_VLAN_TPID1_DEFAULT 0x0

/*[register] CSR_EGSY_VLAN_CP_TAG*/
#define CSR_EGSY_VLAN_CP_TAG
#define CSR_EGSY_VLAN_CP_TAG_ADDRESS 0x18
#define CSR_EGSY_VLAN_CP_TAG_NUM     1
#define CSR_EGSY_VLAN_CP_TAG_INC     0x4
#define CSR_EGSY_VLAN_CP_TAG_TYPE    REG_TYPE_RW
#define CSR_EGSY_VLAN_CP_TAG_DEFAULT 0x0

/*[register] CSR_EGSY_PN_THR*/
#define CSR_EGSY_PN_THR
#define CSR_EGSY_PN_THR_ADDRESS 0x1c
#define CSR_EGSY_PN_THR_NUM     1
#define CSR_EGSY_PN_THR_INC     0x4
#define CSR_EGSY_PN_THR_TYPE    REG_TYPE_RW
#define CSR_EGSY_PN_THR_DEFAULT 0x0

/*[register] CSR_EGSY_MTU*/
#define CSR_EGSY_MTU
#define CSR_EGSY_MTU_ADDRESS 0x20
#define CSR_EGSY_MTU_NUM     1
#define CSR_EGSY_MTU_INC     0x4
#define CSR_EGSY_MTU_TYPE    REG_TYPE_RW
#define CSR_EGSY_MTU_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_DATAIN0*/
#define CSR_EGSY_GCM_DATAIN0
#define CSR_EGSY_GCM_DATAIN0_ADDRESS 0x24
#define CSR_EGSY_GCM_DATAIN0_NUM     1
#define CSR_EGSY_GCM_DATAIN0_INC     0x4
#define CSR_EGSY_GCM_DATAIN0_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_DATAIN0_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_DATAIN1*/
#define CSR_EGSY_GCM_DATAIN1
#define CSR_EGSY_GCM_DATAIN1_ADDRESS 0x28
#define CSR_EGSY_GCM_DATAIN1_NUM     1
#define CSR_EGSY_GCM_DATAIN1_INC     0x4
#define CSR_EGSY_GCM_DATAIN1_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_DATAIN1_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_DATAIN2*/
#define CSR_EGSY_GCM_DATAIN2
#define CSR_EGSY_GCM_DATAIN2_ADDRESS 0x2c
#define CSR_EGSY_GCM_DATAIN2_NUM     1
#define CSR_EGSY_GCM_DATAIN2_INC     0x4
#define CSR_EGSY_GCM_DATAIN2_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_DATAIN2_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_DATAIN3*/
#define CSR_EGSY_GCM_DATAIN3
#define CSR_EGSY_GCM_DATAIN3_ADDRESS 0x30
#define CSR_EGSY_GCM_DATAIN3_NUM     1
#define CSR_EGSY_GCM_DATAIN3_INC     0x4
#define CSR_EGSY_GCM_DATAIN3_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_DATAIN3_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_KEY0*/
#define CSR_EGSY_GCM_KEY0
#define CSR_EGSY_GCM_KEY0_ADDRESS 0x34
#define CSR_EGSY_GCM_KEY0_NUM     1
#define CSR_EGSY_GCM_KEY0_INC     0x4
#define CSR_EGSY_GCM_KEY0_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_KEY0_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_KEY1*/
#define CSR_EGSY_GCM_KEY1
#define CSR_EGSY_GCM_KEY1_ADDRESS 0x38
#define CSR_EGSY_GCM_KEY1_NUM     1
#define CSR_EGSY_GCM_KEY1_INC     0x4
#define CSR_EGSY_GCM_KEY1_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_KEY1_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_KEY2*/
#define CSR_EGSY_GCM_KEY2
#define CSR_EGSY_GCM_KEY2_ADDRESS 0x3c
#define CSR_EGSY_GCM_KEY2_NUM     1
#define CSR_EGSY_GCM_KEY2_INC     0x4
#define CSR_EGSY_GCM_KEY2_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_KEY2_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_KEY3*/
#define CSR_EGSY_GCM_KEY3
#define CSR_EGSY_GCM_KEY3_ADDRESS 0x40
#define CSR_EGSY_GCM_KEY3_NUM     1
#define CSR_EGSY_GCM_KEY3_INC     0x4
#define CSR_EGSY_GCM_KEY3_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_KEY3_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_IV0*/
#define CSR_EGSY_GCM_IV0
#define CSR_EGSY_GCM_IV0_ADDRESS 0x44
#define CSR_EGSY_GCM_IV0_NUM     1
#define CSR_EGSY_GCM_IV0_INC     0x4
#define CSR_EGSY_GCM_IV0_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_IV0_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_IV1*/
#define CSR_EGSY_GCM_IV1
#define CSR_EGSY_GCM_IV1_ADDRESS 0x48
#define CSR_EGSY_GCM_IV1_NUM     1
#define CSR_EGSY_GCM_IV1_INC     0x4
#define CSR_EGSY_GCM_IV1_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_IV1_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_IV2*/
#define CSR_EGSY_GCM_IV2
#define CSR_EGSY_GCM_IV2_ADDRESS 0x4c
#define CSR_EGSY_GCM_IV2_NUM     1
#define CSR_EGSY_GCM_IV2_INC     0x4
#define CSR_EGSY_GCM_IV2_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_IV2_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_IV3*/
#define CSR_EGSY_GCM_IV3
#define CSR_EGSY_GCM_IV3_ADDRESS 0x50
#define CSR_EGSY_GCM_IV3_NUM     1
#define CSR_EGSY_GCM_IV3_INC     0x4
#define CSR_EGSY_GCM_IV3_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_IV3_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_HASHIN0*/
#define CSR_EGSY_GCM_HASHIN0
#define CSR_EGSY_GCM_HASHIN0_ADDRESS 0x54
#define CSR_EGSY_GCM_HASHIN0_NUM     1
#define CSR_EGSY_GCM_HASHIN0_INC     0x4
#define CSR_EGSY_GCM_HASHIN0_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_HASHIN0_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_HASHIN1*/
#define CSR_EGSY_GCM_HASHIN1
#define CSR_EGSY_GCM_HASHIN1_ADDRESS 0x58
#define CSR_EGSY_GCM_HASHIN1_NUM     1
#define CSR_EGSY_GCM_HASHIN1_INC     0x4
#define CSR_EGSY_GCM_HASHIN1_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_HASHIN1_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_HASHIN2*/
#define CSR_EGSY_GCM_HASHIN2
#define CSR_EGSY_GCM_HASHIN2_ADDRESS 0x5c
#define CSR_EGSY_GCM_HASHIN2_NUM     1
#define CSR_EGSY_GCM_HASHIN2_INC     0x4
#define CSR_EGSY_GCM_HASHIN2_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_HASHIN2_DEFAULT 0x0

/*[register] CSR_EGSY_GCM_HASHIN3*/
#define CSR_EGSY_GCM_HASHIN3
#define CSR_EGSY_GCM_HASHIN3_ADDRESS 0x60
#define CSR_EGSY_GCM_HASHIN3_NUM     1
#define CSR_EGSY_GCM_HASHIN3_INC     0x4
#define CSR_EGSY_GCM_HASHIN3_TYPE    REG_TYPE_RW
#define CSR_EGSY_GCM_HASHIN3_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_DATAOUT0*/
#define EGSY_GCM_CSR_DATAOUT0
#define EGSY_GCM_CSR_DATAOUT0_ADDRESS 0x64
#define EGSY_GCM_CSR_DATAOUT0_NUM     1
#define EGSY_GCM_CSR_DATAOUT0_INC     0x4
#define EGSY_GCM_CSR_DATAOUT0_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_DATAOUT0_DEFAULT 0x0

/*[register] EGSYGCM_CSR_DATAOUT1*/
#define EGSYGCM_CSR_DATAOUT1
#define EGSYGCM_CSR_DATAOUT1_ADDRESS 0x68
#define EGSYGCM_CSR_DATAOUT1_NUM     1
#define EGSYGCM_CSR_DATAOUT1_INC     0x4
#define EGSYGCM_CSR_DATAOUT1_TYPE    REG_TYPE_RO
#define EGSYGCM_CSR_DATAOUT1_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_DATAOUT2*/
#define EGSY_GCM_CSR_DATAOUT2
#define EGSY_GCM_CSR_DATAOUT2_ADDRESS 0x6c
#define EGSY_GCM_CSR_DATAOUT2_NUM     1
#define EGSY_GCM_CSR_DATAOUT2_INC     0x4
#define EGSY_GCM_CSR_DATAOUT2_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_DATAOUT2_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_DATAOUT3*/
#define EGSY_GCM_CSR_DATAOUT3
#define EGSY_GCM_CSR_DATAOUT3_ADDRESS 0x70
#define EGSY_GCM_CSR_DATAOUT3_NUM     1
#define EGSY_GCM_CSR_DATAOUT3_INC     0x4
#define EGSY_GCM_CSR_DATAOUT3_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_DATAOUT3_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_HASHOUT0*/
#define EGSY_GCM_CSR_HASHOUT0
#define EGSY_GCM_CSR_HASHOUT0_ADDRESS 0x74
#define EGSY_GCM_CSR_HASHOUT0_NUM     1
#define EGSY_GCM_CSR_HASHOUT0_INC     0x4
#define EGSY_GCM_CSR_HASHOUT0_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_HASHOUT0_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_HASHOUT1*/
#define EGSY_GCM_CSR_HASHOUT1
#define EGSY_GCM_CSR_HASHOUT1_ADDRESS 0x78
#define EGSY_GCM_CSR_HASHOUT1_NUM     1
#define EGSY_GCM_CSR_HASHOUT1_INC     0x4
#define EGSY_GCM_CSR_HASHOUT1_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_HASHOUT1_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_HASHOUT2*/
#define EGSY_GCM_CSR_HASHOUT2
#define EGSY_GCM_CSR_HASHOUT2_ADDRESS 0x7c
#define EGSY_GCM_CSR_HASHOUT2_NUM     1
#define EGSY_GCM_CSR_HASHOUT2_INC     0x4
#define EGSY_GCM_CSR_HASHOUT2_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_HASHOUT2_DEFAULT 0x0

/*[register] EGSY_GCM_CSR_HASHOUT3*/
#define EGSY_GCM_CSR_HASHOUT3
#define EGSY_GCM_CSR_HASHOUT3_ADDRESS 0x80
#define EGSY_GCM_CSR_HASHOUT3_NUM     1
#define EGSY_GCM_CSR_HASHOUT3_INC     0x4
#define EGSY_GCM_CSR_HASHOUT3_TYPE    REG_TYPE_RO
#define EGSY_GCM_CSR_HASHOUT3_DEFAULT 0x0

/*[register] EGSY_EGEBUF_CSR_DEBUG*/
#define EGSY_EGEBUF_CSR_DEBUG
#define EGSY_EGEBUF_CSR_DEBUG_ADDRESS 0x84
#define EGSY_EGEBUF_CSR_DEBUG_NUM     1
#define EGSY_EGEBUF_CSR_DEBUG_INC     0x4
#define EGSY_EGEBUF_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_EGEBUF_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_PFMT_CSR_DEBUG*/
#define EGSY_PFMT_CSR_DEBUG
#define EGSY_PFMT_CSR_DEBUG_ADDRESS 0x88
#define EGSY_PFMT_CSR_DEBUG_NUM     1
#define EGSY_PFMT_CSR_DEBUG_INC     0x4
#define EGSY_PFMT_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_PFMT_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG*/
#define EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG
#define EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG_ADDRESS 0x8c
#define EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG_NUM     1
#define EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG_INC     0x4
#define EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_GCM_MULT_LENA_LSB_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG*/
#define EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG
#define EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG_ADDRESS 0x90
#define EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG_NUM     1
#define EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG_INC     0x4
#define EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_GCM_MULT_LENA_MSB_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG*/
#define EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG
#define EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG_ADDRESS 0x94
#define EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG_NUM     1
#define EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG_INC     0x4
#define EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_GCM_MULT_LENC_LSB_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG*/
#define EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG
#define EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG_ADDRESS 0x98
#define EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG_NUM     1
#define EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG_INC     0x4
#define EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_GCM_MULT_LENC_MSB_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG*/
#define EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG
#define EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG_ADDRESS 0x9c
#define EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG_NUM     1
#define EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG_INC     0x4
#define EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_GCM_MULT_DATA_CNT_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG*/
#define EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG
#define EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_ADDRESS 0xa0
#define EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_NUM     1
#define EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_INC     0x4
#define EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_TYPE    REG_TYPE_RO
#define EGSY_AES_GCM_COUNTER_INCR_CSR_DEBUG_DEFAULT 0x0

/*[register] EGSY_CSR_BUSY_SIGNAL*/
#define EGSY_CSR_BUSY_SIGNAL
#define EGSY_CSR_BUSY_SIGNAL_ADDRESS 0xa4
#define EGSY_CSR_BUSY_SIGNAL_NUM     1
#define EGSY_CSR_BUSY_SIGNAL_INC     0x4
#define EGSY_CSR_BUSY_SIGNAL_TYPE    REG_TYPE_RO
#define EGSY_CSR_BUSY_SIGNAL_DEFAULT 0x0

/*[register] EGSY_MACSEC_SPARE_REG1*/
#define EGSY_MACSEC_SPARE_REG1
#define EGSY_MACSEC_SPARE_REG1_ADDRESS 0xa8
#define EGSY_MACSEC_SPARE_REG1_NUM     1
#define EGSY_MACSEC_SPARE_REG1_INC     0x4
#define EGSY_MACSEC_SPARE_REG1_TYPE    REG_TYPE_RW
#define EGSY_MACSEC_SPARE_REG1_DEFAULT 0x0

/*[register] EGSY_SCTRL_DROP_EN*/
#define EGSY_SCTRL_DROP_EN
#define EGSY_SCTRL_DROP_EN_ADDRESS 0xac
#define EGSY_SCTRL_DROP_EN_NUM     1
#define EGSY_SCTRL_DROP_EN_INC     0x4
#define EGSY_SCTRL_DROP_EN_TYPE    REG_TYPE_RW
#define EGSY_SCTRL_DROP_EN_DEFAULT 0x0

/*[register] EGSY_ECTRL_ENABLE*/
#define EGSY_ECTRL_ENABLE
#define EGSY_ECTRL_ENABLE_ADDRESS 0xb0
#define EGSY_ECTRL_ENABLE_NUM     1
#define EGSY_ECTRL_ENABLE_INC     0x4
#define EGSY_ECTRL_ENABLE_TYPE    REG_TYPE_RW
#define EGSY_ECTRL_ENABLE_DEFAULT 0x0

/*[register] EGSY_EMAC_REGS*/
#define EGSY_EMAC_REGS
#define EGSY_EMAC_REGS_ADDRESS 0xb4
#define EGSY_EMAC_REGS_NUM     1
#define EGSY_EMAC_REGS_INC     0x4
#define EGSY_EMAC_REGS_TYPE    REG_TYPE_RW
#define EGSY_EMAC_REGS_DEFAULT 0x0

/*[register] EGSY_INT*/
#define EGSY_INT
#define EGSY_INT_ADDRESS 0xb8
#define EGSY_INT_NUM     1
#define EGSY_INT_INC     0x4
#define EGSY_INT_TYPE    REG_TYPE_RW
#define EGSY_INT_DEFAULT 0x0

/*[register] EGSY_INT_EN*/
#define EGSY_INT_EN
#define EGSY_INT_EN_ADDRESS 0xbc
#define EGSY_INT_EN_NUM     1
#define EGSY_INT_EN_INC     0x4
#define EGSY_INT_EN_TYPE    REG_TYPE_RW
#define EGSY_INT_EN_DEFAULT 0x0

/*[register] EGSY_SA_EXP*/
#define EGSY_SA_EXP
#define EGSY_SA_EXP_ADDRESS 0xc0
#define EGSY_SA_EXP_NUM     1
#define EGSY_SA_EXP_INC     0x4
#define EGSY_SA_EXP_TYPE    REG_TYPE_RW
#define EGSY_SA_EXP_DEFAULT 0x0

/*[register] EGSY_SA_THR*/
#define EGSY_SA_THR
#define EGSY_SA_THR_ADDRESS 0xc4
#define EGSY_SA_THR_NUM     1
#define EGSY_SA_THR_INC     0x4
#define EGSY_SA_THR_TYPE    REG_TYPE_RW
#define EGSY_SA_THR_DEFAULT 0x0

/*[register] EGECC_ERR_REG*/
#define EGECC_ERR_REG
#define EGECC_ERR_REG_ADDRESS 0xc8
#define EGECC_ERR_REG_NUM     1
#define EGECC_ERR_REG_INC     0x4
#define EGECC_ERR_REG_TYPE    REG_TYPE_RW
#define EGECC_ERR_REG_DEFAULT 0x0

/*[register] EGPRC_ECC_ERR1_ADDR*/
#define EGPRC_ECC_ERR1_ADDR
#define EGPRC_ECC_ERR1_ADDR_ADDRESS 0xcc
#define EGPRC_ECC_ERR1_ADDR_NUM     1
#define EGPRC_ECC_ERR1_ADDR_INC     0x4
#define EGPRC_ECC_ERR1_ADDR_TYPE    REG_TYPE_RW
#define EGPRC_ECC_ERR1_ADDR_DEFAULT 0x0

/*[register] EGPRC_ECC_ERR2_ADDR*/
#define EGPRC_ECC_ERR2_ADDR
#define EGPRC_ECC_ERR2_ADDR_ADDRESS 0xd0
#define EGPRC_ECC_ERR2_ADDR_NUM     1
#define EGPRC_ECC_ERR2_ADDR_INC     0x4
#define EGPRC_ECC_ERR2_ADDR_TYPE    REG_TYPE_RW
#define EGPRC_ECC_ERR2_ADDR_DEFAULT 0x0

/*[register] EGLKUP_CTLF_ECC_ERR_ADDR*/
#define EGLKUP_CTLF_ECC_ERR_ADDR
#define EGLKUP_CTLF_ECC_ERR_ADDR_ADDRESS 0xd4
#define EGLKUP_CTLF_ECC_ERR_ADDR_NUM     1
#define EGLKUP_CTLF_ECC_ERR_ADDR_INC     0x4
#define EGLKUP_CTLF_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define EGLKUP_CTLF_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] PFMT_SC_SA_ECC_ERR_ADDR*/
#define PFMT_SC_SA_ECC_ERR_ADDR
#define PFMT_SC_SA_ECC_ERR_ADDR_ADDRESS 0xd8
#define PFMT_SC_SA_ECC_ERR_ADDR_NUM     1
#define PFMT_SC_SA_ECC_ERR_ADDR_INC     0x4
#define PFMT_SC_SA_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define PFMT_SC_SA_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] EGSY_SMIB_ECC_ERR_ADDR*/
#define EGSY_SMIB_ECC_ERR_ADDR
#define EGSY_SMIB_ECC_ERR_ADDR_ADDRESS 0xdc
#define EGSY_SMIB_ECC_ERR_ADDR_NUM     1
#define EGSY_SMIB_ECC_ERR_ADDR_INC     0x4
#define EGSY_SMIB_ECC_ERR_ADDR_TYPE    REG_TYPE_RW
#define EGSY_SMIB_ECC_ERR_ADDR_DEFAULT 0x0

/*[register] EGSY_ENABLE_ECC*/
#define EGSY_ENABLE_ECC
#define EGSY_ENABLE_ECC_ADDRESS 0xe0
#define EGSY_ENABLE_ECC_NUM     1
#define EGSY_ENABLE_ECC_INC     0x4
#define EGSY_ENABLE_ECC_TYPE    REG_TYPE_RW
#define EGSY_ENABLE_ECC_DEFAULT 0x0

/*[register] EG_TABLE_CMD*/
#define EG_TABLE_CMD
#define EG_TABLE_CMD_ADDRESS 0x100
#define EG_TABLE_CMD_NUM     1
#define EG_TABLE_CMD_INC     0x4
#define EG_TABLE_CMD_TYPE    REG_TYPE_RW
#define EG_TABLE_CMD_DEFAULT 0x0

/*[register] EG_TABLE_DATA*/
#define EG_TABLE_DATA
#define EG_TABLE_DATA_ADDRESS 0x140
#define EG_TABLE_DATA_NUM     1
#define EG_TABLE_DATA_INC     0x40
#define EG_TABLE_DATA_TYPE    REG_TYPE_RW
#define EG_TABLE_DATA_DEFAULT 0x0

/*[table] EMAC1_REV*/
#define EMAC1_REV
#define EMAC1_REV_ADDRESS 0x0
#define EMAC1_REV_NUM     1
#define EMAC1_REV_INC     0x4
#define EMAC1_REV_TYPE    REG_TYPE_RO
#define EMAC1_REV_DEFAULT 0x0

/*[table] EMAC1_SCRATCH*/
#define EMAC1_SCRATCH
#define EMAC1_SCRATCH_ADDRESS 0x4
#define EMAC1_SCRATCH_NUM     1
#define EMAC1_SCRATCH_INC     0x4
#define EMAC1_SCRATCH_TYPE    REG_TYPE_RW
#define EMAC1_SCRATCH_DEFAULT 0x0

/*[table] EMAC1_COMMAND_CONFIG*/
#define EMAC1_COMMAND_CONFIG
#define EMAC1_COMMAND_CONFIG_ADDRESS 0x8
#define EMAC1_COMMAND_CONFIG_NUM     1
#define EMAC1_COMMAND_CONFIG_INC     0x4
#define EMAC1_COMMAND_CONFIG_TYPE    REG_TYPE_RW
#define EMAC1_COMMAND_CONFIG_DEFAULT 0x0

/*[table] EMAC1_MAC_0*/
#define EMAC1_MAC_0
#define EMAC1_MAC_0_ADDRESS 0xc
#define EMAC1_MAC_0_NUM     1
#define EMAC1_MAC_0_INC     0x4
#define EMAC1_MAC_0_TYPE    REG_TYPE_RW
#define EMAC1_MAC_0_DEFAULT 0x0

/*[table] EMAC1_MAC_1*/
#define EMAC1_MAC_1
#define EMAC1_MAC_1_ADDRESS 0x10
#define EMAC1_MAC_1_NUM     1
#define EMAC1_MAC_1_INC     0x4
#define EMAC1_MAC_1_TYPE    REG_TYPE_RW
#define EMAC1_MAC_1_DEFAULT 0x0

/*[table] EMAC1_FRM_LENGTH*/
#define EMAC1_FRM_LENGTH
#define EMAC1_FRM_LENGTH_ADDRESS 0x14
#define EMAC1_FRM_LENGTH_NUM     1
#define EMAC1_FRM_LENGTH_INC     0x4
#define EMAC1_FRM_LENGTH_TYPE    REG_TYPE_RW
#define EMAC1_FRM_LENGTH_DEFAULT 0x0

/*[table] EMAC1_PAUSE_QUANT*/
#define EMAC1_PAUSE_QUANT
#define EMAC1_PAUSE_QUANT_ADDRESS 0x18
#define EMAC1_PAUSE_QUANT_NUM     1
#define EMAC1_PAUSE_QUANT_INC     0x4
#define EMAC1_PAUSE_QUANT_TYPE    REG_TYPE_RW
#define EMAC1_PAUSE_QUANT_DEFAULT 0x0

/*[table] EMAC1_RX_SECTION_EMPTY*/
#define EMAC1_RX_SECTION_EMPTY
#define EMAC1_RX_SECTION_EMPTY_ADDRESS 0x1c
#define EMAC1_RX_SECTION_EMPTY_NUM     1
#define EMAC1_RX_SECTION_EMPTY_INC     0x4
#define EMAC1_RX_SECTION_EMPTY_TYPE    REG_TYPE_RW
#define EMAC1_RX_SECTION_EMPTY_DEFAULT 0x0

/*[table] EMAC1_RX_SECTION_FULL*/
#define EMAC1_RX_SECTION_FULL
#define EMAC1_RX_SECTION_FULL_ADDRESS 0x20
#define EMAC1_RX_SECTION_FULL_NUM     1
#define EMAC1_RX_SECTION_FULL_INC     0x4
#define EMAC1_RX_SECTION_FULL_TYPE    REG_TYPE_RW
#define EMAC1_RX_SECTION_FULL_DEFAULT 0x0

/*[table] EMAC1_TX_SECTION_EMPTY*/
#define EMAC1_TX_SECTION_EMPTY
#define EMAC1_TX_SECTION_EMPTY_ADDRESS 0x24
#define EMAC1_TX_SECTION_EMPTY_NUM     1
#define EMAC1_TX_SECTION_EMPTY_INC     0x4
#define EMAC1_TX_SECTION_EMPTY_TYPE    REG_TYPE_RW
#define EMAC1_TX_SECTION_EMPTY_DEFAULT 0x0

/*[table] EMAC1_TX_SECTION_FULL*/
#define EMAC1_TX_SECTION_FULL
#define EMAC1_TX_SECTION_FULL_ADDRESS 0x28
#define EMAC1_TX_SECTION_FULL_NUM     1
#define EMAC1_TX_SECTION_FULL_INC     0x4
#define EMAC1_TX_SECTION_FULL_TYPE    REG_TYPE_RW
#define EMAC1_TX_SECTION_FULL_DEFAULT 0x0

/*[table] EMAC1_RX_ALMOST_EMPTY*/
#define EMAC1_RX_ALMOST_EMPTY
#define EMAC1_RX_ALMOST_EMPTY_ADDRESS 0x2c
#define EMAC1_RX_ALMOST_EMPTY_NUM     1
#define EMAC1_RX_ALMOST_EMPTY_INC     0x4
#define EMAC1_RX_ALMOST_EMPTY_TYPE    REG_TYPE_RW
#define EMAC1_RX_ALMOST_EMPTY_DEFAULT 0x0

/*[table] EMAC1_RX_ALMOST_FULL*/
#define EMAC1_RX_ALMOST_FULL
#define EMAC1_RX_ALMOST_FULL_ADDRESS 0x30
#define EMAC1_RX_ALMOST_FULL_NUM     1
#define EMAC1_RX_ALMOST_FULL_INC     0x4
#define EMAC1_RX_ALMOST_FULL_TYPE    REG_TYPE_RW
#define EMAC1_RX_ALMOST_FULL_DEFAULT 0x0

/*[table] EMAC1_TX_ALMOST_EMPTY*/
#define EMAC1_TX_ALMOST_EMPTY
#define EMAC1_TX_ALMOST_EMPTY_ADDRESS 0x34
#define EMAC1_TX_ALMOST_EMPTY_NUM     1
#define EMAC1_TX_ALMOST_EMPTY_INC     0x4
#define EMAC1_TX_ALMOST_EMPTY_TYPE    REG_TYPE_RW
#define EMAC1_TX_ALMOST_EMPTY_DEFAULT 0x0

/*[table] EMAC1_TX_ALMOST_FULL*/
#define EMAC1_TX_ALMOST_FULL
#define EMAC1_TX_ALMOST_FULL_ADDRESS 0x38
#define EMAC1_TX_ALMOST_FULL_NUM     1
#define EMAC1_TX_ALMOST_FULL_INC     0x4
#define EMAC1_TX_ALMOST_FULL_TYPE    REG_TYPE_RW
#define EMAC1_TX_ALMOST_FULL_DEFAULT 0x0

/*[table] EMAC1_MDIO_ADDR0*/
#define EMAC1_MDIO_ADDR0
#define EMAC1_MDIO_ADDR0_ADDRESS 0x3c
#define EMAC1_MDIO_ADDR0_NUM     1
#define EMAC1_MDIO_ADDR0_INC     0x4
#define EMAC1_MDIO_ADDR0_TYPE    REG_TYPE_RW
#define EMAC1_MDIO_ADDR0_DEFAULT 0x0

/*[table] EMAC1_MDIO_ADDR1*/
#define EMAC1_MDIO_ADDR1
#define EMAC1_MDIO_ADDR1_ADDRESS 0x40
#define EMAC1_MDIO_ADDR1_NUM     1
#define EMAC1_MDIO_ADDR1_INC     0x4
#define EMAC1_MDIO_ADDR1_TYPE    REG_TYPE_RW
#define EMAC1_MDIO_ADDR1_DEFAULT 0x0

/*[table] EMAC1_REG_STATUS*/
#define EMAC1_REG_STATUS
#define EMAC1_REG_STATUS_ADDRESS 0x58
#define EMAC1_REG_STATUS_NUM     1
#define EMAC1_REG_STATUS_INC     0x4
#define EMAC1_REG_STATUS_TYPE    REG_TYPE_RO
#define EMAC1_REG_STATUS_DEFAULT 0x0

/*[table] EMAC1_TX_IPG_LENGTH*/
#define EMAC1_TX_IPG_LENGTH
#define EMAC1_TX_IPG_LENGTH_ADDRESS 0x5c
#define EMAC1_TX_IPG_LENGTH_NUM     1
#define EMAC1_TX_IPG_LENGTH_INC     0x4
#define EMAC1_TX_IPG_LENGTH_TYPE    REG_TYPE_RW
#define EMAC1_TX_IPG_LENGTH_DEFAULT 0x0

/*[table] EMAC1_AMACID*/
#define EMAC1_AMACID
#define EMAC1_AMACID_ADDRESS 0x60
#define EMAC1_AMACID_NUM     1
#define EMAC1_AMACID_INC     0x8
#define EMAC1_AMACID_TYPE    REG_TYPE_RO
#define EMAC1_AMACID_DEFAULT 0x0

/*[table] EMAC1_AFRAMESTRANSMITTEDOK*/
#define EMAC1_AFRAMESTRANSMITTEDOK
#define EMAC1_AFRAMESTRANSMITTEDOK_ADDRESS 0x68
#define EMAC1_AFRAMESTRANSMITTEDOK_NUM     1
#define EMAC1_AFRAMESTRANSMITTEDOK_INC     0x4
#define EMAC1_AFRAMESTRANSMITTEDOK_TYPE    REG_TYPE_RO
#define EMAC1_AFRAMESTRANSMITTEDOK_DEFAULT 0x0

/*[table] EMAC1_AFRAMESRECEIVEDOK*/
#define EMAC1_AFRAMESRECEIVEDOK
#define EMAC1_AFRAMESRECEIVEDOK_ADDRESS 0x6c
#define EMAC1_AFRAMESRECEIVEDOK_NUM     1
#define EMAC1_AFRAMESRECEIVEDOK_INC     0x4
#define EMAC1_AFRAMESRECEIVEDOK_TYPE    REG_TYPE_RO
#define EMAC1_AFRAMESRECEIVEDOK_DEFAULT 0x0

/*[table] EMAC1_AFRAMECHECKSEQUENCEERRORS*/
#define EMAC1_AFRAMECHECKSEQUENCEERRORS
#define EMAC1_AFRAMECHECKSEQUENCEERRORS_ADDRESS 0x70
#define EMAC1_AFRAMECHECKSEQUENCEERRORS_NUM     1
#define EMAC1_AFRAMECHECKSEQUENCEERRORS_INC     0x4
#define EMAC1_AFRAMECHECKSEQUENCEERRORS_TYPE    REG_TYPE_RO
#define EMAC1_AFRAMECHECKSEQUENCEERRORS_DEFAULT 0x0

/*[table] EMAC1_AALIGNMENTERRORS*/
#define EMAC1_AALIGNMENTERRORS
#define EMAC1_AALIGNMENTERRORS_ADDRESS 0x74
#define EMAC1_AALIGNMENTERRORS_NUM     1
#define EMAC1_AALIGNMENTERRORS_INC     0x4
#define EMAC1_AALIGNMENTERRORS_TYPE    REG_TYPE_RO
#define EMAC1_AALIGNMENTERRORS_DEFAULT 0x0

/*[table] EMAC1_AOCTETSTRANSMITTEDOK*/
#define EMAC1_AOCTETSTRANSMITTEDOK
#define EMAC1_AOCTETSTRANSMITTEDOK_ADDRESS 0x78
#define EMAC1_AOCTETSTRANSMITTEDOK_NUM     1
#define EMAC1_AOCTETSTRANSMITTEDOK_INC     0x4
#define EMAC1_AOCTETSTRANSMITTEDOK_TYPE    REG_TYPE_RO
#define EMAC1_AOCTETSTRANSMITTEDOK_DEFAULT 0x0

/*[table] EMAC1_AOCTETSRECEIVEDOK*/
#define EMAC1_AOCTETSRECEIVEDOK
#define EMAC1_AOCTETSRECEIVEDOK_ADDRESS 0x7c
#define EMAC1_AOCTETSRECEIVEDOK_NUM     1
#define EMAC1_AOCTETSRECEIVEDOK_INC     0x4
#define EMAC1_AOCTETSRECEIVEDOK_TYPE    REG_TYPE_RO
#define EMAC1_AOCTETSRECEIVEDOK_DEFAULT 0x0

/*[table] EMAC1_ATXPAUSEMACCTRLFRAMES*/
#define EMAC1_ATXPAUSEMACCTRLFRAMES
#define EMAC1_ATXPAUSEMACCTRLFRAMES_ADDRESS 0x80
#define EMAC1_ATXPAUSEMACCTRLFRAMES_NUM     1
#define EMAC1_ATXPAUSEMACCTRLFRAMES_INC     0x4
#define EMAC1_ATXPAUSEMACCTRLFRAMES_TYPE    REG_TYPE_RO
#define EMAC1_ATXPAUSEMACCTRLFRAMES_DEFAULT 0x0

/*[table] EMAC1_ARXPAUSEMACCTRLFRAMES*/
#define EMAC1_ARXPAUSEMACCTRLFRAMES
#define EMAC1_ARXPAUSEMACCTRLFRAMES_ADDRESS 0x84
#define EMAC1_ARXPAUSEMACCTRLFRAMES_NUM     1
#define EMAC1_ARXPAUSEMACCTRLFRAMES_INC     0x4
#define EMAC1_ARXPAUSEMACCTRLFRAMES_TYPE    REG_TYPE_RO
#define EMAC1_ARXPAUSEMACCTRLFRAMES_DEFAULT 0x0

/*[table] EMAC1_IFINERRORS*/
#define EMAC1_IFINERRORS
#define EMAC1_IFINERRORS_ADDRESS 0x88
#define EMAC1_IFINERRORS_NUM     1
#define EMAC1_IFINERRORS_INC     0x4
#define EMAC1_IFINERRORS_TYPE    REG_TYPE_RO
#define EMAC1_IFINERRORS_DEFAULT 0x0

/*[table] EMAC1_IFOUTERRORS*/
#define EMAC1_IFOUTERRORS
#define EMAC1_IFOUTERRORS_ADDRESS 0x8c
#define EMAC1_IFOUTERRORS_NUM     1
#define EMAC1_IFOUTERRORS_INC     0x4
#define EMAC1_IFOUTERRORS_TYPE    REG_TYPE_RO
#define EMAC1_IFOUTERRORS_DEFAULT 0x0

/*[table] EMAC1_IFINUCASTPKTS*/
#define EMAC1_IFINUCASTPKTS
#define EMAC1_IFINUCASTPKTS_ADDRESS 0x90
#define EMAC1_IFINUCASTPKTS_NUM     1
#define EMAC1_IFINUCASTPKTS_INC     0x4
#define EMAC1_IFINUCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC1_IFINUCASTPKTS_DEFAULT 0x0

/*[table] EMAC1_IFINMULTICASTPKTS*/
#define EMAC1_IFINMULTICASTPKTS
#define EMAC1_IFINMULTICASTPKTS_ADDRESS 0x94
#define EMAC1_IFINMULTICASTPKTS_NUM     1
#define EMAC1_IFINMULTICASTPKTS_INC     0x4
#define EMAC1_IFINMULTICASTPKTS_TYPE    REG_TYPE_RO
#define EMAC1_IFINMULTICASTPKTS_DEFAULT 0x0

/*[table] EMAC1_IFINBROADCASTPKTS*/
#define EMAC1_IFINBROADCASTPKTS
#define EMAC1_IFINBROADCASTPKTS_ADDRESS 0x98
#define EMAC1_IFINBROADCASTPKTS_NUM     1
#define EMAC1_IFINBROADCASTPKTS_INC     0x4
#define EMAC1_IFINBROADCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC1_IFINBROADCASTPKTS_DEFAULT 0x0

/*[table] EMAC1_IFOUTDISCARDS*/
#define EMAC1_IFOUTDISCARDS
#define EMAC1_IFOUTDISCARDS_ADDRESS 0x9c
#define EMAC1_IFOUTDISCARDS_NUM     1
#define EMAC1_IFOUTDISCARDS_INC     0x4
#define EMAC1_IFOUTDISCARDS_TYPE    REG_TYPE_RO
#define EMAC1_IFOUTDISCARDS_DEFAULT 0x0

/*[table] EMAC1_IFOUTUCASTPKTS*/
#define EMAC1_IFOUTUCASTPKTS
#define EMAC1_IFOUTUCASTPKTS_ADDRESS 0xa0
#define EMAC1_IFOUTUCASTPKTS_NUM     1
#define EMAC1_IFOUTUCASTPKTS_INC     0x4
#define EMAC1_IFOUTUCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC1_IFOUTUCASTPKTS_DEFAULT 0x0

/*[table] EMAC1_IFOUTMULTICASTPKTS*/
#define EMAC1_IFOUTMULTICASTPKTS
#define EMAC1_IFOUTMULTICASTPKTS_ADDRESS 0xa4
#define EMAC1_IFOUTMULTICASTPKTS_NUM     1
#define EMAC1_IFOUTMULTICASTPKTS_INC     0x4
#define EMAC1_IFOUTMULTICASTPKTS_TYPE    REG_TYPE_RO
#define EMAC1_IFOUTMULTICASTPKTS_DEFAULT 0x0

/*[table] EMAC1_IFOUTBROADCASTPKTS*/
#define EMAC1_IFOUTBROADCASTPKTS
#define EMAC1_IFOUTBROADCASTPKTS_ADDRESS 0xa8
#define EMAC1_IFOUTBROADCASTPKTS_NUM     1
#define EMAC1_IFOUTBROADCASTPKTS_INC     0x4
#define EMAC1_IFOUTBROADCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC1_IFOUTBROADCASTPKTS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSDROPEVENTS*/
#define EMAC1_ETHERSTATSDROPEVENTS
#define EMAC1_ETHERSTATSDROPEVENTS_ADDRESS 0xac
#define EMAC1_ETHERSTATSDROPEVENTS_NUM     1
#define EMAC1_ETHERSTATSDROPEVENTS_INC     0x4
#define EMAC1_ETHERSTATSDROPEVENTS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSDROPEVENTS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSOCTETS*/
#define EMAC1_ETHERSTATSOCTETS
#define EMAC1_ETHERSTATSOCTETS_ADDRESS 0xb0
#define EMAC1_ETHERSTATSOCTETS_NUM     1
#define EMAC1_ETHERSTATSOCTETS_INC     0x4
#define EMAC1_ETHERSTATSOCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSOCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS*/
#define EMAC1_ETHERSTATSPKTS
#define EMAC1_ETHERSTATSPKTS_ADDRESS 0xb4
#define EMAC1_ETHERSTATSPKTS_NUM     1
#define EMAC1_ETHERSTATSPKTS_INC     0x4
#define EMAC1_ETHERSTATSPKTS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSUNDERSIZEPKTS*/
#define EMAC1_ETHERSTATSUNDERSIZEPKTS
#define EMAC1_ETHERSTATSUNDERSIZEPKTS_ADDRESS 0xb8
#define EMAC1_ETHERSTATSUNDERSIZEPKTS_NUM     1
#define EMAC1_ETHERSTATSUNDERSIZEPKTS_INC     0x4
#define EMAC1_ETHERSTATSUNDERSIZEPKTS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSUNDERSIZEPKTS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSOVERSIZEPKTS*/
#define EMAC1_ETHERSTATSOVERSIZEPKTS
#define EMAC1_ETHERSTATSOVERSIZEPKTS_ADDRESS 0xbc
#define EMAC1_ETHERSTATSOVERSIZEPKTS_NUM     1
#define EMAC1_ETHERSTATSOVERSIZEPKTS_INC     0x4
#define EMAC1_ETHERSTATSOVERSIZEPKTS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSOVERSIZEPKTS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS64OCTETS*/
#define EMAC1_ETHERSTATSPKTS64OCTETS
#define EMAC1_ETHERSTATSPKTS64OCTETS_ADDRESS 0xc0
#define EMAC1_ETHERSTATSPKTS64OCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS64OCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS64OCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS64OCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS65TO127OCTETS*/
#define EMAC1_ETHERSTATSPKTS65TO127OCTETS
#define EMAC1_ETHERSTATSPKTS65TO127OCTETS_ADDRESS 0xc4
#define EMAC1_ETHERSTATSPKTS65TO127OCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS65TO127OCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS65TO127OCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS65TO127OCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS128TO255OCTETS*/
#define EMAC1_ETHERSTATSPKTS128TO255OCTETS
#define EMAC1_ETHERSTATSPKTS128TO255OCTETS_ADDRESS 0xc8
#define EMAC1_ETHERSTATSPKTS128TO255OCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS128TO255OCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS128TO255OCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS128TO255OCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS256TO511OCTETS*/
#define EMAC1_ETHERSTATSPKTS256TO511OCTETS
#define EMAC1_ETHERSTATSPKTS256TO511OCTETS_ADDRESS 0xcc
#define EMAC1_ETHERSTATSPKTS256TO511OCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS256TO511OCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS256TO511OCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS256TO511OCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS512TO1023OCTETS*/
#define EMAC1_ETHERSTATSPKTS512TO1023OCTETS
#define EMAC1_ETHERSTATSPKTS512TO1023OCTETS_ADDRESS 0xd0
#define EMAC1_ETHERSTATSPKTS512TO1023OCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS512TO1023OCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS512TO1023OCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS512TO1023OCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS1024TO1518OCTETS*/
#define EMAC1_ETHERSTATSPKTS1024TO1518OCTETS
#define EMAC1_ETHERSTATSPKTS1024TO1518OCTETS_ADDRESS 0xd4
#define EMAC1_ETHERSTATSPKTS1024TO1518OCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS1024TO1518OCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS1024TO1518OCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS1024TO1518OCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSPKTS1519TOXOCTETS*/
#define EMAC1_ETHERSTATSPKTS1519TOXOCTETS
#define EMAC1_ETHERSTATSPKTS1519TOXOCTETS_ADDRESS 0xd8
#define EMAC1_ETHERSTATSPKTS1519TOXOCTETS_NUM     1
#define EMAC1_ETHERSTATSPKTS1519TOXOCTETS_INC     0x4
#define EMAC1_ETHERSTATSPKTS1519TOXOCTETS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSPKTS1519TOXOCTETS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSJABBERS*/
#define EMAC1_ETHERSTATSJABBERS
#define EMAC1_ETHERSTATSJABBERS_ADDRESS 0xdc
#define EMAC1_ETHERSTATSJABBERS_NUM     1
#define EMAC1_ETHERSTATSJABBERS_INC     0x4
#define EMAC1_ETHERSTATSJABBERS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSJABBERS_DEFAULT 0x0

/*[table] EMAC1_ETHERSTATSFRAGMENTS*/
#define EMAC1_ETHERSTATSFRAGMENTS
#define EMAC1_ETHERSTATSFRAGMENTS_ADDRESS 0xe0
#define EMAC1_ETHERSTATSFRAGMENTS_NUM     1
#define EMAC1_ETHERSTATSFRAGMENTS_INC     0x4
#define EMAC1_ETHERSTATSFRAGMENTS_TYPE    REG_TYPE_RO
#define EMAC1_ETHERSTATSFRAGMENTS_DEFAULT 0x0

/*[table] EMAC2_REV*/
#define EMAC2_REV
#define EMAC2_REV_ADDRESS 0x0
#define EMAC2_REV_NUM     1
#define EMAC2_REV_INC     0x4
#define EMAC2_REV_TYPE    REG_TYPE_RO
#define EMAC2_REV_DEFAULT 0x0

/*[table] EMAC2_SCRATCH*/
#define EMAC2_SCRATCH
#define EMAC2_SCRATCH_ADDRESS 0x4
#define EMAC2_SCRATCH_NUM     1
#define EMAC2_SCRATCH_INC     0x4
#define EMAC2_SCRATCH_TYPE    REG_TYPE_RW
#define EMAC2_SCRATCH_DEFAULT 0x0

/*[table] EMAC2_COMMAND_CONFIG*/
#define EMAC2_COMMAND_CONFIG
#define EMAC2_COMMAND_CONFIG_ADDRESS 0x8
#define EMAC2_COMMAND_CONFIG_NUM     1
#define EMAC2_COMMAND_CONFIG_INC     0x4
#define EMAC2_COMMAND_CONFIG_TYPE    REG_TYPE_RW
#define EMAC2_COMMAND_CONFIG_DEFAULT 0x0

/*[table] EMAC2_MAC_0*/
#define EMAC2_MAC_0
#define EMAC2_MAC_0_ADDRESS 0xc
#define EMAC2_MAC_0_NUM     1
#define EMAC2_MAC_0_INC     0x4
#define EMAC2_MAC_0_TYPE    REG_TYPE_RW
#define EMAC2_MAC_0_DEFAULT 0x0

/*[table] EMAC2_MAC_1*/
#define EMAC2_MAC_1
#define EMAC2_MAC_1_ADDRESS 0x10
#define EMAC2_MAC_1_NUM     1
#define EMAC2_MAC_1_INC     0x4
#define EMAC2_MAC_1_TYPE    REG_TYPE_RW
#define EMAC2_MAC_1_DEFAULT 0x0

/*[table] EMAC2_FRM_LENGTH*/
#define EMAC2_FRM_LENGTH
#define EMAC2_FRM_LENGTH_ADDRESS 0x14
#define EMAC2_FRM_LENGTH_NUM     1
#define EMAC2_FRM_LENGTH_INC     0x4
#define EMAC2_FRM_LENGTH_TYPE    REG_TYPE_RW
#define EMAC2_FRM_LENGTH_DEFAULT 0x0

/*[table] EMAC2_PAUSE_QUANT*/
#define EMAC2_PAUSE_QUANT
#define EMAC2_PAUSE_QUANT_ADDRESS 0x18
#define EMAC2_PAUSE_QUANT_NUM     1
#define EMAC2_PAUSE_QUANT_INC     0x4
#define EMAC2_PAUSE_QUANT_TYPE    REG_TYPE_RW
#define EMAC2_PAUSE_QUANT_DEFAULT 0x0

/*[table] EMAC2_RX_SECTION_EMPTY*/
#define EMAC2_RX_SECTION_EMPTY
#define EMAC2_RX_SECTION_EMPTY_ADDRESS 0x1c
#define EMAC2_RX_SECTION_EMPTY_NUM     1
#define EMAC2_RX_SECTION_EMPTY_INC     0x4
#define EMAC2_RX_SECTION_EMPTY_TYPE    REG_TYPE_RW
#define EMAC2_RX_SECTION_EMPTY_DEFAULT 0x0

/*[table] EMAC2_RX_SECTION_FULL*/
#define EMAC2_RX_SECTION_FULL
#define EMAC2_RX_SECTION_FULL_ADDRESS 0x20
#define EMAC2_RX_SECTION_FULL_NUM     1
#define EMAC2_RX_SECTION_FULL_INC     0x4
#define EMAC2_RX_SECTION_FULL_TYPE    REG_TYPE_RW
#define EMAC2_RX_SECTION_FULL_DEFAULT 0x0

/*[table] EMAC2_TX_SECTION_EMPTY*/
#define EMAC2_TX_SECTION_EMPTY
#define EMAC2_TX_SECTION_EMPTY_ADDRESS 0x24
#define EMAC2_TX_SECTION_EMPTY_NUM     1
#define EMAC2_TX_SECTION_EMPTY_INC     0x4
#define EMAC2_TX_SECTION_EMPTY_TYPE    REG_TYPE_RW
#define EMAC2_TX_SECTION_EMPTY_DEFAULT 0x0

/*[table] EMAC2_TX_SECTION_FULL*/
#define EMAC2_TX_SECTION_FULL
#define EMAC2_TX_SECTION_FULL_ADDRESS 0x28
#define EMAC2_TX_SECTION_FULL_NUM     1
#define EMAC2_TX_SECTION_FULL_INC     0x4
#define EMAC2_TX_SECTION_FULL_TYPE    REG_TYPE_RW
#define EMAC2_TX_SECTION_FULL_DEFAULT 0x0

/*[table] EMAC2_RX_ALMOST_EMPTY*/
#define EMAC2_RX_ALMOST_EMPTY
#define EMAC2_RX_ALMOST_EMPTY_ADDRESS 0x2c
#define EMAC2_RX_ALMOST_EMPTY_NUM     1
#define EMAC2_RX_ALMOST_EMPTY_INC     0x4
#define EMAC2_RX_ALMOST_EMPTY_TYPE    REG_TYPE_RW
#define EMAC2_RX_ALMOST_EMPTY_DEFAULT 0x0

/*[table] EMAC2_RX_ALMOST_FULL*/
#define EMAC2_RX_ALMOST_FULL
#define EMAC2_RX_ALMOST_FULL_ADDRESS 0x30
#define EMAC2_RX_ALMOST_FULL_NUM     1
#define EMAC2_RX_ALMOST_FULL_INC     0x4
#define EMAC2_RX_ALMOST_FULL_TYPE    REG_TYPE_RW
#define EMAC2_RX_ALMOST_FULL_DEFAULT 0x0

/*[table] EMAC2_TX_ALMOST_EMPTY*/
#define EMAC2_TX_ALMOST_EMPTY
#define EMAC2_TX_ALMOST_EMPTY_ADDRESS 0x34
#define EMAC2_TX_ALMOST_EMPTY_NUM     1
#define EMAC2_TX_ALMOST_EMPTY_INC     0x4
#define EMAC2_TX_ALMOST_EMPTY_TYPE    REG_TYPE_RW
#define EMAC2_TX_ALMOST_EMPTY_DEFAULT 0x0

/*[table] EMAC2_TX_ALMOST_FULL*/
#define EMAC2_TX_ALMOST_FULL
#define EMAC2_TX_ALMOST_FULL_ADDRESS 0x38
#define EMAC2_TX_ALMOST_FULL_NUM     1
#define EMAC2_TX_ALMOST_FULL_INC     0x4
#define EMAC2_TX_ALMOST_FULL_TYPE    REG_TYPE_RW
#define EMAC2_TX_ALMOST_FULL_DEFAULT 0x0

/*[table] EMAC2_MDIO_ADDR0*/
#define EMAC2_MDIO_ADDR0
#define EMAC2_MDIO_ADDR0_ADDRESS 0x3c
#define EMAC2_MDIO_ADDR0_NUM     1
#define EMAC2_MDIO_ADDR0_INC     0x4
#define EMAC2_MDIO_ADDR0_TYPE    REG_TYPE_RW
#define EMAC2_MDIO_ADDR0_DEFAULT 0x0

/*[table] EMAC2_MDIO_ADDR1*/
#define EMAC2_MDIO_ADDR1
#define EMAC2_MDIO_ADDR1_ADDRESS 0x40
#define EMAC2_MDIO_ADDR1_NUM     1
#define EMAC2_MDIO_ADDR1_INC     0x4
#define EMAC2_MDIO_ADDR1_TYPE    REG_TYPE_RW
#define EMAC2_MDIO_ADDR1_DEFAULT 0x0

/*[table] EMAC2_REG_STATUS*/
#define EMAC2_REG_STATUS
#define EMAC2_REG_STATUS_ADDRESS 0x58
#define EMAC2_REG_STATUS_NUM     1
#define EMAC2_REG_STATUS_INC     0x4
#define EMAC2_REG_STATUS_TYPE    REG_TYPE_RO
#define EMAC2_REG_STATUS_DEFAULT 0x0

/*[table] EMAC2_TX_IPG_LENGTH*/
#define EMAC2_TX_IPG_LENGTH
#define EMAC2_TX_IPG_LENGTH_ADDRESS 0x5c
#define EMAC2_TX_IPG_LENGTH_NUM     1
#define EMAC2_TX_IPG_LENGTH_INC     0x4
#define EMAC2_TX_IPG_LENGTH_TYPE    REG_TYPE_RW
#define EMAC2_TX_IPG_LENGTH_DEFAULT 0x0

/*[table] EMAC2_AMACID*/
#define EMAC2_AMACID
#define EMAC2_AMACID_ADDRESS 0x60
#define EMAC2_AMACID_NUM     1
#define EMAC2_AMACID_INC     0x8
#define EMAC2_AMACID_TYPE    REG_TYPE_RO
#define EMAC2_AMACID_DEFAULT 0x0

/*[table] EMAC2_AFRAMESTRANSMITTEDOK*/
#define EMAC2_AFRAMESTRANSMITTEDOK
#define EMAC2_AFRAMESTRANSMITTEDOK_ADDRESS 0x68
#define EMAC2_AFRAMESTRANSMITTEDOK_NUM     1
#define EMAC2_AFRAMESTRANSMITTEDOK_INC     0x4
#define EMAC2_AFRAMESTRANSMITTEDOK_TYPE    REG_TYPE_RO
#define EMAC2_AFRAMESTRANSMITTEDOK_DEFAULT 0x0

/*[table] EMAC2_AFRAMESRECEIVEDOK*/
#define EMAC2_AFRAMESRECEIVEDOK
#define EMAC2_AFRAMESRECEIVEDOK_ADDRESS 0x6c
#define EMAC2_AFRAMESRECEIVEDOK_NUM     1
#define EMAC2_AFRAMESRECEIVEDOK_INC     0x4
#define EMAC2_AFRAMESRECEIVEDOK_TYPE    REG_TYPE_RO
#define EMAC2_AFRAMESRECEIVEDOK_DEFAULT 0x0

/*[table] EMAC2_AFRAMECHECKSEQUENCEERRORS*/
#define EMAC2_AFRAMECHECKSEQUENCEERRORS
#define EMAC2_AFRAMECHECKSEQUENCEERRORS_ADDRESS 0x70
#define EMAC2_AFRAMECHECKSEQUENCEERRORS_NUM     1
#define EMAC2_AFRAMECHECKSEQUENCEERRORS_INC     0x4
#define EMAC2_AFRAMECHECKSEQUENCEERRORS_TYPE    REG_TYPE_RO
#define EMAC2_AFRAMECHECKSEQUENCEERRORS_DEFAULT 0x0

/*[table] EMAC2_AALIGNMENTERRORS*/
#define EMAC2_AALIGNMENTERRORS
#define EMAC2_AALIGNMENTERRORS_ADDRESS 0x74
#define EMAC2_AALIGNMENTERRORS_NUM     1
#define EMAC2_AALIGNMENTERRORS_INC     0x4
#define EMAC2_AALIGNMENTERRORS_TYPE    REG_TYPE_RO
#define EMAC2_AALIGNMENTERRORS_DEFAULT 0x0

/*[table] EMAC2_AOCTETSTRANSMITTEDOK*/
#define EMAC2_AOCTETSTRANSMITTEDOK
#define EMAC2_AOCTETSTRANSMITTEDOK_ADDRESS 0x78
#define EMAC2_AOCTETSTRANSMITTEDOK_NUM     1
#define EMAC2_AOCTETSTRANSMITTEDOK_INC     0x4
#define EMAC2_AOCTETSTRANSMITTEDOK_TYPE    REG_TYPE_RO
#define EMAC2_AOCTETSTRANSMITTEDOK_DEFAULT 0x0

/*[table] EMAC2_AOCTETSRECEIVEDOK*/
#define EMAC2_AOCTETSRECEIVEDOK
#define EMAC2_AOCTETSRECEIVEDOK_ADDRESS 0x7c
#define EMAC2_AOCTETSRECEIVEDOK_NUM     1
#define EMAC2_AOCTETSRECEIVEDOK_INC     0x4
#define EMAC2_AOCTETSRECEIVEDOK_TYPE    REG_TYPE_RO
#define EMAC2_AOCTETSRECEIVEDOK_DEFAULT 0x0

/*[table] EMAC2_ATXPAUSEMACCTRLFRAMES*/
#define EMAC2_ATXPAUSEMACCTRLFRAMES
#define EMAC2_ATXPAUSEMACCTRLFRAMES_ADDRESS 0x80
#define EMAC2_ATXPAUSEMACCTRLFRAMES_NUM     1
#define EMAC2_ATXPAUSEMACCTRLFRAMES_INC     0x4
#define EMAC2_ATXPAUSEMACCTRLFRAMES_TYPE    REG_TYPE_RO
#define EMAC2_ATXPAUSEMACCTRLFRAMES_DEFAULT 0x0

/*[table] EMAC2_ARXPAUSEMACCTRLFRAMES*/
#define EMAC2_ARXPAUSEMACCTRLFRAMES
#define EMAC2_ARXPAUSEMACCTRLFRAMES_ADDRESS 0x84
#define EMAC2_ARXPAUSEMACCTRLFRAMES_NUM     1
#define EMAC2_ARXPAUSEMACCTRLFRAMES_INC     0x4
#define EMAC2_ARXPAUSEMACCTRLFRAMES_TYPE    REG_TYPE_RO
#define EMAC2_ARXPAUSEMACCTRLFRAMES_DEFAULT 0x0

/*[table] EMAC2_IFINERRORS*/
#define EMAC2_IFINERRORS
#define EMAC2_IFINERRORS_ADDRESS 0x88
#define EMAC2_IFINERRORS_NUM     1
#define EMAC2_IFINERRORS_INC     0x4
#define EMAC2_IFINERRORS_TYPE    REG_TYPE_RO
#define EMAC2_IFINERRORS_DEFAULT 0x0

/*[table] EMAC2_IFOUTERRORS*/
#define EMAC2_IFOUTERRORS
#define EMAC2_IFOUTERRORS_ADDRESS 0x8c
#define EMAC2_IFOUTERRORS_NUM     1
#define EMAC2_IFOUTERRORS_INC     0x4
#define EMAC2_IFOUTERRORS_TYPE    REG_TYPE_RO
#define EMAC2_IFOUTERRORS_DEFAULT 0x0

/*[table] EMAC2_IFINUCASTPKTS*/
#define EMAC2_IFINUCASTPKTS
#define EMAC2_IFINUCASTPKTS_ADDRESS 0x90
#define EMAC2_IFINUCASTPKTS_NUM     1
#define EMAC2_IFINUCASTPKTS_INC     0x4
#define EMAC2_IFINUCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC2_IFINUCASTPKTS_DEFAULT 0x0

/*[table] EMAC2_IFINMULTICASTPKTS*/
#define EMAC2_IFINMULTICASTPKTS
#define EMAC2_IFINMULTICASTPKTS_ADDRESS 0x94
#define EMAC2_IFINMULTICASTPKTS_NUM     1
#define EMAC2_IFINMULTICASTPKTS_INC     0x4
#define EMAC2_IFINMULTICASTPKTS_TYPE    REG_TYPE_RO
#define EMAC2_IFINMULTICASTPKTS_DEFAULT 0x0

/*[table] EMAC2_IFINBROADCASTPKTS*/
#define EMAC2_IFINBROADCASTPKTS
#define EMAC2_IFINBROADCASTPKTS_ADDRESS 0x98
#define EMAC2_IFINBROADCASTPKTS_NUM     1
#define EMAC2_IFINBROADCASTPKTS_INC     0x4
#define EMAC2_IFINBROADCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC2_IFINBROADCASTPKTS_DEFAULT 0x0

/*[table] EMAC2_IFOUTDISCARDS*/
#define EMAC2_IFOUTDISCARDS
#define EMAC2_IFOUTDISCARDS_ADDRESS 0x9c
#define EMAC2_IFOUTDISCARDS_NUM     1
#define EMAC2_IFOUTDISCARDS_INC     0x4
#define EMAC2_IFOUTDISCARDS_TYPE    REG_TYPE_RO
#define EMAC2_IFOUTDISCARDS_DEFAULT 0x0

/*[table] EMAC2_IFOUTUCASTPKTS*/
#define EMAC2_IFOUTUCASTPKTS
#define EMAC2_IFOUTUCASTPKTS_ADDRESS 0xa0
#define EMAC2_IFOUTUCASTPKTS_NUM     1
#define EMAC2_IFOUTUCASTPKTS_INC     0x4
#define EMAC2_IFOUTUCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC2_IFOUTUCASTPKTS_DEFAULT 0x0

/*[table] EMAC2_IFOUTMULTICASTPKTS*/
#define EMAC2_IFOUTMULTICASTPKTS
#define EMAC2_IFOUTMULTICASTPKTS_ADDRESS 0xa4
#define EMAC2_IFOUTMULTICASTPKTS_NUM     1
#define EMAC2_IFOUTMULTICASTPKTS_INC     0x4
#define EMAC2_IFOUTMULTICASTPKTS_TYPE    REG_TYPE_RO
#define EMAC2_IFOUTMULTICASTPKTS_DEFAULT 0x0

/*[table] EMAC2_IFOUTBROADCASTPKTS*/
#define EMAC2_IFOUTBROADCASTPKTS
#define EMAC2_IFOUTBROADCASTPKTS_ADDRESS 0xa8
#define EMAC2_IFOUTBROADCASTPKTS_NUM     1
#define EMAC2_IFOUTBROADCASTPKTS_INC     0x4
#define EMAC2_IFOUTBROADCASTPKTS_TYPE    REG_TYPE_RO
#define EMAC2_IFOUTBROADCASTPKTS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSDROPEVENTS*/
#define EMAC2_ETHERSTATSDROPEVENTS
#define EMAC2_ETHERSTATSDROPEVENTS_ADDRESS 0xac
#define EMAC2_ETHERSTATSDROPEVENTS_NUM     1
#define EMAC2_ETHERSTATSDROPEVENTS_INC     0x4
#define EMAC2_ETHERSTATSDROPEVENTS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSDROPEVENTS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSOCTETS*/
#define EMAC2_ETHERSTATSOCTETS
#define EMAC2_ETHERSTATSOCTETS_ADDRESS 0xb0
#define EMAC2_ETHERSTATSOCTETS_NUM     1
#define EMAC2_ETHERSTATSOCTETS_INC     0x4
#define EMAC2_ETHERSTATSOCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSOCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS*/
#define EMAC2_ETHERSTATSPKTS
#define EMAC2_ETHERSTATSPKTS_ADDRESS 0xb4
#define EMAC2_ETHERSTATSPKTS_NUM     1
#define EMAC2_ETHERSTATSPKTS_INC     0x4
#define EMAC2_ETHERSTATSPKTS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSUNDERSIZEPKTS*/
#define EMAC2_ETHERSTATSUNDERSIZEPKTS
#define EMAC2_ETHERSTATSUNDERSIZEPKTS_ADDRESS 0xb8
#define EMAC2_ETHERSTATSUNDERSIZEPKTS_NUM     1
#define EMAC2_ETHERSTATSUNDERSIZEPKTS_INC     0x4
#define EMAC2_ETHERSTATSUNDERSIZEPKTS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSUNDERSIZEPKTS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSOVERSIZEPKTS*/
#define EMAC2_ETHERSTATSOVERSIZEPKTS
#define EMAC2_ETHERSTATSOVERSIZEPKTS_ADDRESS 0xbc
#define EMAC2_ETHERSTATSOVERSIZEPKTS_NUM     1
#define EMAC2_ETHERSTATSOVERSIZEPKTS_INC     0x4
#define EMAC2_ETHERSTATSOVERSIZEPKTS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSOVERSIZEPKTS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS64OCTETS*/
#define EMAC2_ETHERSTATSPKTS64OCTETS
#define EMAC2_ETHERSTATSPKTS64OCTETS_ADDRESS 0xc0
#define EMAC2_ETHERSTATSPKTS64OCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS64OCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS64OCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS64OCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS65TO127OCTETS*/
#define EMAC2_ETHERSTATSPKTS65TO127OCTETS
#define EMAC2_ETHERSTATSPKTS65TO127OCTETS_ADDRESS 0xc4
#define EMAC2_ETHERSTATSPKTS65TO127OCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS65TO127OCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS65TO127OCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS65TO127OCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS128TO255OCTETS*/
#define EMAC2_ETHERSTATSPKTS128TO255OCTETS
#define EMAC2_ETHERSTATSPKTS128TO255OCTETS_ADDRESS 0xc8
#define EMAC2_ETHERSTATSPKTS128TO255OCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS128TO255OCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS128TO255OCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS128TO255OCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS256TO511OCTETS*/
#define EMAC2_ETHERSTATSPKTS256TO511OCTETS
#define EMAC2_ETHERSTATSPKTS256TO511OCTETS_ADDRESS 0xcc
#define EMAC2_ETHERSTATSPKTS256TO511OCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS256TO511OCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS256TO511OCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS256TO511OCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS512TO1023OCTETS*/
#define EMAC2_ETHERSTATSPKTS512TO1023OCTETS
#define EMAC2_ETHERSTATSPKTS512TO1023OCTETS_ADDRESS 0xd0
#define EMAC2_ETHERSTATSPKTS512TO1023OCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS512TO1023OCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS512TO1023OCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS512TO1023OCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS1024TO1518OCTETS*/
#define EMAC2_ETHERSTATSPKTS1024TO1518OCTETS
#define EMAC2_ETHERSTATSPKTS1024TO1518OCTETS_ADDRESS 0xd4
#define EMAC2_ETHERSTATSPKTS1024TO1518OCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS1024TO1518OCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS1024TO1518OCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS1024TO1518OCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSPKTS1519TOXOCTETS*/
#define EMAC2_ETHERSTATSPKTS1519TOXOCTETS
#define EMAC2_ETHERSTATSPKTS1519TOXOCTETS_ADDRESS 0xd8
#define EMAC2_ETHERSTATSPKTS1519TOXOCTETS_NUM     1
#define EMAC2_ETHERSTATSPKTS1519TOXOCTETS_INC     0x4
#define EMAC2_ETHERSTATSPKTS1519TOXOCTETS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSPKTS1519TOXOCTETS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSJABBERS*/
#define EMAC2_ETHERSTATSJABBERS
#define EMAC2_ETHERSTATSJABBERS_ADDRESS 0xdc
#define EMAC2_ETHERSTATSJABBERS_NUM     1
#define EMAC2_ETHERSTATSJABBERS_INC     0x4
#define EMAC2_ETHERSTATSJABBERS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSJABBERS_DEFAULT 0x0

/*[table] EMAC2_ETHERSTATSFRAGMENTS*/
#define EMAC2_ETHERSTATSFRAGMENTS
#define EMAC2_ETHERSTATSFRAGMENTS_ADDRESS 0xe0
#define EMAC2_ETHERSTATSFRAGMENTS_NUM     1
#define EMAC2_ETHERSTATSFRAGMENTS_INC     0x4
#define EMAC2_ETHERSTATSFRAGMENTS_TYPE    REG_TYPE_RO
#define EMAC2_ETHERSTATSFRAGMENTS_DEFAULT 0x0

#endif
