// Copyright (c) 2013 Qualcomm Atheros, Inc.  All rights reserved.
// $ATH_LICENSE_HW_HDR_C$
//
// DO NOT EDIT!  This file is automatically generated
//               These definitions are tied to a particular hardware layout


#ifndef _MPDU_LENGTH_USER1_H_
#define _MPDU_LENGTH_USER1_H_
#if !defined(__ASSEMBLER__)
#endif

// ################ START SUMMARY #################
//
//	Dword	Fields
//	0	struct mpdu_length mpdu_length_user1;
//
// ################ END SUMMARY #################

#define NUM_OF_DWORDS_MPDU_LENGTH_USER1 1

struct mpdu_length_user1 {
    struct            mpdu_length                       mpdu_length_user1;
};

/*

struct mpdu_length mpdu_length_user1
			
			See definition of MPDU_LENGTH
*/

#define MPDU_LENGTH_USER1_0_MPDU_LENGTH_MPDU_LENGTH_USER1_OFFSET     0x00000000
#define MPDU_LENGTH_USER1_0_MPDU_LENGTH_MPDU_LENGTH_USER1_LSB        0
#define MPDU_LENGTH_USER1_0_MPDU_LENGTH_MPDU_LENGTH_USER1_MASK       0xffffffff


#endif // _MPDU_LENGTH_USER1_H_
