/*
 * Copyright (c) 2015, The Linux Foundation. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef MDSS_QPIC_ERTFT_PANEL_H
#define MDSS_QPIC_ERTFT_PANEL_H

/**
 * SSD1963 commands. ER panel */
#define OP_SSD1963_TEARING_EFFECT_LINE_ON	0x35
#define OP_SSD1963_SET_LCD_MODE			0xB0
#define OP_SSD1963_SET_HOR_PERIOD		0xB4
#define OP_SSD1963_SET_VER_PERIOD		0xB6
#define OP_SSD1963_SET_GPIO_CONFIG		0xB8
#define OP_SSD1963_SET_GPIO_VAL			0xBA
#define OP_SSD1963_SET_POST_PROC		0xBC
#define OP_SSD1963_SET_PWM_CONFIG		0xBE
#define OP_SSD1963_SET_PLL			0xE0
#define OP_SSD1963_SET_PLL_MN			0xE2
#define OP_SSD1963_SET_LSHIFT_FREQ		0xE6
#define OP_SSD1963_SET_PIXEL_DATA_IFACE		0xF0
#define OP_SSD1963_SET_DBC_CONFIG		0xD0

#endif
