


#ifndef __MAP_WIFICMN_REG_H_
#define __MAP_WIFICMN_REG_H_

#include "../../hw/mac_reg_structs.h"

#define INT_STATUS_HF_TIMER_MSB             WIFICMN_LF_HF_WDT_INT_STATUS_HF_TIMER_MSB
#define INT_STATUS_HF_TIMER_LSB             WIFICMN_LF_HF_WDT_INT_STATUS_HF_TIMER_LSB
#define INT_STATUS_HF_TIMER_MASK            WIFICMN_LF_HF_WDT_INT_STATUS_HF_TIMER_MASK
#define INT_STATUS_HF_TIMER_GET(x)          WIFICMN_LF_HF_WDT_INT_STATUS_HF_TIMER_GET(x)
#define INT_STATUS_HF_TIMER_SET(x)          WIFICMN_LF_HF_WDT_INT_STATUS_HF_TIMER_SET(x)
#define INT_STATUS_LF_TIMER3_MSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER3_MSB
#define INT_STATUS_LF_TIMER3_LSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER3_LSB
#define INT_STATUS_LF_TIMER3_MASK           WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER3_MASK
#define INT_STATUS_LF_TIMER3_GET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER3_GET(x)
#define INT_STATUS_LF_TIMER3_SET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER3_SET(x)
#define INT_STATUS_LF_TIMER2_MSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER2_MSB
#define INT_STATUS_LF_TIMER2_LSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER2_LSB
#define INT_STATUS_LF_TIMER2_MASK           WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER2_MASK
#define INT_STATUS_LF_TIMER2_GET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER2_GET(x)
#define INT_STATUS_LF_TIMER2_SET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER2_SET(x)
#define INT_STATUS_LF_TIMER1_MSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER1_MSB
#define INT_STATUS_LF_TIMER1_LSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER1_LSB
#define INT_STATUS_LF_TIMER1_MASK           WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER1_MASK
#define INT_STATUS_LF_TIMER1_GET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER1_GET(x)
#define INT_STATUS_LF_TIMER1_SET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER1_SET(x)
#define INT_STATUS_LF_TIMER0_MSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER0_MSB
#define INT_STATUS_LF_TIMER0_LSB            WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER0_LSB
#define INT_STATUS_LF_TIMER0_MASK           WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER0_MASK
#define INT_STATUS_LF_TIMER0_GET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER0_GET(x)
#define INT_STATUS_LF_TIMER0_SET(x)         WIFICMN_LF_HF_WDT_INT_STATUS_LF_TIMER0_SET(x)


#endif
